artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/47056b251c1f41248566a5f1becfc027/artifacts
end_time: 1762268378174
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: 47056b251c1f41248566a5f1becfc027
run_name: seed222_tiny
source_name: ''
source_type: 4
source_version: ''
start_time: 1762268287876
status: 3
tags: []
user_id: kn
