artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522/0c6475dcc78e4c73be8c4140447e4ed5/artifacts
end_time: 1763095979400
entry_point_name: ''
experiment_id: '195331767355654522'
lifecycle_stage: active
run_id: 0c6475dcc78e4c73be8c4140447e4ed5
run_name: large_batch_sched_boost_seed777_2025-11-14_04-29-47
source_name: ''
source_type: 4
source_version: ''
start_time: 1763094610616
status: 3
tags: []
user_id: kn
