artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/479183f6b1ae44f8ac1aad1eded620dc/artifacts
end_time: 1764289492849
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 479183f6b1ae44f8ac1aad1eded620dc
run_name: sched_boost_lr035_seed222_2025-11-27_23-38-29
source_name: ''
source_type: 4
source_version: ''
start_time: 1764286721521
status: 3
tags: []
user_id: vscode
