artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/203034696812255868/3a0187c406374dab91ef9e800fe437da/artifacts
end_time: null
entry_point_name: ''
experiment_id: '203034696812255868'
lifecycle_stage: active
run_id: 3a0187c406374dab91ef9e800fe437da
run_name: large_batch_sched_boost_seed777_2025-11-08_14-44-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1762613105451
status: 1
tags: []
user_id: kn
