artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829/0c456c8fc1c2401688cfa849e21f257b/artifacts
end_time: 1762715308082
entry_point_name: ''
experiment_id: '157436571815778829'
lifecycle_stage: active
run_id: 0c456c8fc1c2401688cfa849e21f257b
run_name: large_batch_sched_boost_seed222_2025-11-09_18-34-12
source_name: ''
source_type: 4
source_version: ''
start_time: 1762713276941
status: 3
tags: []
user_id: kn
