artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/c48fe8d63eba4f82bcb77f7186945b0f/artifacts
end_time: 1764843830256
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: c48fe8d63eba4f82bcb77f7186945b0f
run_name: polish_seed555_2025-12-04_09-25-54_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764843747161
status: 3
tags: []
user_id: vscode
