artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/e2b528141aa04ff39d46f0e9bfd06a6e/artifacts
end_time: 1766164018198
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: e2b528141aa04ff39d46f0e9bfd06a6e
run_name: polish_lr_low_seed101_2025-12-19_15-55-17
source_name: ''
source_type: 4
source_version: ''
start_time: 1766159729813
status: 3
tags: []
user_id: vscode
