artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/c768ec33dfb24172b2a6abe0983a8a36/artifacts
end_time: 1763913960177
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: c768ec33dfb24172b2a6abe0983a8a36
run_name: sched_boost_seed1337_2025-11-23_15-33-22
source_name: ''
source_type: 4
source_version: ''
start_time: 1763912040191
status: 3
tags: []
user_id: vscode
