artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813
creation_time: 1764276898153
experiment_id: '450284739565994813'
last_update_time: 1764276898153
lifecycle_stage: active
name: dynamic_topoqa
