artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/391a78a30f4b41e8bef7db2a7791bebd/artifacts
end_time: 1762565587697
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: 391a78a30f4b41e8bef7db2a7791bebd
run_name: sched_boost_seed222_2025-11-08_01-04-58
source_name: ''
source_type: 4
source_version: ''
start_time: 1762563916981
status: 3
tags: []
user_id: kn
