artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171
creation_time: 1766081797667
experiment_id: '384024837216329171'
last_update_time: 1766081797667
lifecycle_stage: active
name: dynamic_topoqa
