artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/90d45f8e9f9e4d63acfa896594f4f43c/artifacts
end_time: 1762108517946
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 90d45f8e9f9e4d63acfa896594f4f43c
run_name: large_batch_sched_boost_seed777_2025-11-02_17-49-09
source_name: ''
source_type: 4
source_version: ''
start_time: 1762105763377
status: 3
tags: []
user_id: kn
