artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/ba6e15c571db4bf8a4edca66bf4297c6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: ba6e15c571db4bf8a4edca66bf4297c6
run_name: sched_boost_seed222_cuda_fastdev_2025-11-04_14-39-11
source_name: ''
source_type: 4
source_version: ''
start_time: 1762267164822
status: 1
tags: []
user_id: kn
