artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932/440bf98d5ac0417b9f5de1babafdb38d/artifacts
end_time: 1764608970589
entry_point_name: ''
experiment_id: '553929320275185932'
lifecycle_stage: active
run_id: 440bf98d5ac0417b9f5de1babafdb38d
run_name: sched_boost_lean_seed222_2025-12-01_15-11-21_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764608441526
status: 3
tags: []
user_id: vscode
