artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/757735313826032059/fb4071c15f944b3abcaf525c335b3f6e/artifacts
end_time: 1763814225762
entry_point_name: ''
experiment_id: '757735313826032059'
lifecycle_stage: active
run_id: fb4071c15f944b3abcaf525c335b3f6e
run_name: large_batch_sched_boost_seed1337_2025-11-22_12-01-43
source_name: ''
source_type: 4
source_version: ''
start_time: 1763812935464
status: 3
tags: []
user_id: vscode
