paths:
  graph: ../../new_graph_builder/output/24d_edges_adjusted_dataset/graph_data
  train_labels: ./train.csv
  val_labels: ./val.csv
  save_dir: ./training_runs
model:
  pooling_type: mean
  attention_head: 8
dataloader:
  batch_size: 16
  num_workers: 0
  seed: 222
trainer:
  accelerator: cpu
  devices: 1
  precision: 32
  num_epochs: 200
  accumulate_grad_batches: 16
optimizer:
  learning_rate: 0.005
scheduler:
  type: reduce_on_plateau
  factor: 0.4
  patience: 12
early_stopping:
  patience: 25
selection:
  use_val_spearman: true
  spearman_min_delta: 0.0
  spearman_weight: 1.0
logging:
  progress_bar_refresh_rate: 0
  log_every_n_steps: 100
mlflow:
  enabled: true
  tracking_uri: ./ml_runs
  experiment: dynamic_topoqa
  run_name: null
  log_artifacts: true
  tags: {}
