artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/ebc28fb786354350a61b09aa60bd35a5/artifacts
end_time: 1764013337364
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: ebc28fb786354350a61b09aa60bd35a5
run_name: latest_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1764012522182
status: 3
tags: []
user_id: vscode
