artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/cc6f595e86464ce39b973ece98efcc8c/artifacts
end_time: 1764843216151
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: cc6f595e86464ce39b973ece98efcc8c
run_name: polish_lr_low_seed555_2025-12-04_09-54-18
source_name: ''
source_type: 4
source_version: ''
start_time: 1764842082054
status: 3
tags: []
user_id: vscode
