artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/203034696812255868/b4a9240849324b4a9ec95591d02060d6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '203034696812255868'
lifecycle_stage: active
run_id: b4a9240849324b4a9ec95591d02060d6
run_name: sched_boost_lr035_seed777_2025-11-08_11-07-38
source_name: ''
source_type: 4
source_version: ''
start_time: 1762600076551
status: 1
tags: []
user_id: kn
