artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/a7ed1f78d8aa4d638f320ddf92d10ba4/artifacts
end_time: 1762280929507
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: a7ed1f78d8aa4d638f320ddf92d10ba4
run_name: seed222_tiny_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1762278508959
status: 3
tags: []
user_id: kn
