artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/cc034506db9b49dabec6961094e1e68c/artifacts
end_time: 1762334693247
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: cc034506db9b49dabec6961094e1e68c
run_name: sched_boost_seed222_2025-11-05_07-45-31
source_name: ''
source_type: 4
source_version: ''
start_time: 1762328747093
status: 3
tags: []
user_id: kn
