artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/263834183455537235/ecde5e16f7d540ee9e6d4fdbcab667c0/artifacts
end_time: 1763859415773
entry_point_name: ''
experiment_id: '263834183455537235'
lifecycle_stage: active
run_id: ecde5e16f7d540ee9e6d4fdbcab667c0
run_name: sched_boost_lr035_seed1337_2025-11-22_22-53-57_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1763859137528
status: 3
tags: []
user_id: vscode
