artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/290449c1dbe441b591a49f725b3d1da1/artifacts
end_time: 1762576441982
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: 290449c1dbe441b591a49f725b3d1da1
run_name: large_batch_sched_boost_seed222_2025-11-08_04-02-25
source_name: ''
source_type: 4
source_version: ''
start_time: 1762574562423
status: 3
tags: []
user_id: kn
