artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/3fc8e6a662d84a60b2c81bef7608d21e/artifacts
end_time: 1764353409834
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 3fc8e6a662d84a60b2c81bef7608d21e
run_name: polish_seed888_2025-11-28_17-12-28
source_name: ''
source_type: 4
source_version: ''
start_time: 1764349961815
status: 3
tags: []
user_id: vscode
