artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/08dac7d77f7c4cf497fe34ba4a380424/artifacts
end_time: 1762091059311
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 08dac7d77f7c4cf497fe34ba4a380424
run_name: sched_boost_seed1337_2025-11-02_12-35-18
source_name: ''
source_type: 4
source_version: ''
start_time: 1762086932634
status: 3
tags: []
user_id: kn
