artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/f4e817a892d34cd58a8ac86e88bde875/artifacts
end_time: 1762551931023
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: f4e817a892d34cd58a8ac86e88bde875
run_name: large_batch_sched_boost_seed222_2025-11-07_21-00-06_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762551139083
status: 3
tags: []
user_id: kn
