artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/84c4bae1cf9341edabef348acc4bcf6e/artifacts
end_time: 1765287885448
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: 84c4bae1cf9341edabef348acc4bcf6e
run_name: polish_seed888_2025-12-09_10-46-11_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1765287388958
status: 3
tags: []
user_id: vscode
