artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/1340926faaa54f7799b7f61fb2caf103/artifacts
end_time: 1766084959550
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: 1340926faaa54f7799b7f61fb2caf103
run_name: large_batch_sched_boost_lean_seed222_2025-12-18_18-50-20
source_name: ''
source_type: 4
source_version: ''
start_time: 1766083827203
status: 3
tags: []
user_id: vscode
