artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/830446690413640518/13b37a1ab64e42d4850ce1e9c04edbc7/artifacts
end_time: 1763283235279
entry_point_name: ''
experiment_id: '830446690413640518'
lifecycle_stage: active
run_id: 13b37a1ab64e42d4850ce1e9c04edbc7
run_name: sched_boost_seed777_2025-11-16_08-20-29
source_name: ''
source_type: 4
source_version: ''
start_time: 1763281258388
status: 3
tags: []
user_id: kn
