artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/cad129ca01fe4ef4bea728ed616ca763/artifacts
end_time: 1764072978898
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: cad129ca01fe4ef4bea728ed616ca763
run_name: large_batch_sched_boost_seed222_2025-11-25_11-53-45
source_name: ''
source_type: 4
source_version: ''
start_time: 1764071666383
status: 3
tags: []
user_id: vscode
