artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/84de999cd39e489aaba4ae7cca4a5d4b/artifacts
end_time: 1765544906645
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: 84de999cd39e489aaba4ae7cca4a5d4b
run_name: polish_seed888_2025-12-12_12-41-01
source_name: ''
source_type: 4
source_version: ''
start_time: 1765543268561
status: 3
tags: []
user_id: vscode
