artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691
creation_time: 1764700856187
experiment_id: '704094476654428691'
last_update_time: 1764700856187
lifecycle_stage: active
name: dynamic_topoqa
