artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/757735313826032059/690d1cc9ac774072aaff2ab4930cccb2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '757735313826032059'
lifecycle_stage: active
run_id: 690d1cc9ac774072aaff2ab4930cccb2
run_name: sched_boost_seed1337_2025-11-22_09-31-22
source_name: ''
source_type: 4
source_version: ''
start_time: 1763803901901
status: 1
tags: []
user_id: vscode
