artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/fc01198a3dae4bfaadb11b6104d7e6d3/artifacts
end_time: 1764098524316
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: fc01198a3dae4bfaadb11b6104d7e6d3
run_name: polish_seed888_2025-11-25_17-17-08_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1764097634079
status: 3
tags: []
user_id: vscode
