artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/14b9b2ef3d814e2c96db749e1d7f2b29/artifacts
end_time: 1765537904032
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: 14b9b2ef3d814e2c96db749e1d7f2b29
run_name: polish_lr_low_seed101_2025-12-12_10-05-34
source_name: ''
source_type: 4
source_version: ''
start_time: 1765533939848
status: 3
tags: []
user_id: vscode
