artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/983626403599653281/2fc4ae4e345d47d083ec0c44e2510e1b/artifacts
end_time: 1762397898391
entry_point_name: ''
experiment_id: '983626403599653281'
lifecycle_stage: active
run_id: 2fc4ae4e345d47d083ec0c44e2510e1b
run_name: sched_boost_seed222_2025-11-05_23-27-09_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762395750337
status: 3
tags: []
user_id: kn
