artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974/366ed9a6a7b3454eab5f013cf5d9c0c3/artifacts
end_time: 1762692479876
entry_point_name: ''
experiment_id: '278908513362295974'
lifecycle_stage: active
run_id: 366ed9a6a7b3454eab5f013cf5d9c0c3
run_name: sched_boost_seed777_2025-11-09_08-46-53_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762691995928
status: 3
tags: []
user_id: kn
