accelerator: cpu
accumulate_grad_batches: 16
attention_head: 8
batch_size: 16
devices: 1
early_stopping_patience: 25
edge_schema:
  bands:
  - label: short
    max_distance: 6.0
    min_distance: 0.0
  - label: medium
    max_distance: 10.0
    min_distance: 6.0
  - label: long
    max_distance: 14.0
    min_distance: 10.0
  dim: 24
  use_layer_norm: true
graph_dir: ../../new_graph_builder/output/pilot_batch/graph_data
learning_rate: 0.005
lr_scheduler_factor: 0.4
lr_scheduler_patience: 12
num_epochs: 5
num_workers: 0
pooling_type: mean
precision: 32
save_dir: ./training_runs
seed: 1337
topology_schema:
  vector_dim: 140
train_label_file: ./train_pilot.csv
val_label_file: ./val_pilot.csv
