artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/b0d23e54fe01474db7c424e7fa5e5054/artifacts
end_time: 1764077951605
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: b0d23e54fe01474db7c424e7fa5e5054
run_name: sched_boost_seed222_2025-11-25_09-32-00_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764077333030
status: 3
tags: []
user_id: vscode
