artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932/52eaf37f5ec14c46b4a0c61c5cb5e926/artifacts
end_time: 1764649753914
entry_point_name: ''
experiment_id: '553929320275185932'
lifecycle_stage: active
run_id: 52eaf37f5ec14c46b4a0c61c5cb5e926
run_name: polish_seed101_2025-12-01_17-16-30_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764648753147
status: 3
tags: []
user_id: vscode
