artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829/906cd271b62349e3b14cd4a9f53c44b6/artifacts
end_time: 1762718067669
entry_point_name: ''
experiment_id: '157436571815778829'
lifecycle_stage: active
run_id: 906cd271b62349e3b14cd4a9f53c44b6
run_name: large_batch_sched_boost_seed777_2025-11-09_19-08-28
source_name: ''
source_type: 4
source_version: ''
start_time: 1762715333291
status: 3
tags: []
user_id: kn
