artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223/19701dfcd3c8484f86f7ce00d54dc615/artifacts
end_time: 1765936523686
entry_point_name: ''
experiment_id: '578842538229463223'
lifecycle_stage: active
run_id: 19701dfcd3c8484f86f7ce00d54dc615
run_name: polish_lr_low_seed888_2025-12-17_01-09-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1765933803936
status: 3
tags: []
user_id: vscode
