artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/860e7c9dcf4f4e0f828746ef7d5525ab/artifacts
end_time: 1765476476988
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: 860e7c9dcf4f4e0f828746ef7d5525ab
run_name: large_batch_sched_boost_lean_seed222_2025-12-11_17-46-16_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1765476367444
status: 3
tags: []
user_id: vscode
