artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/a929877bac9d4c38868b65dd46cc974d/artifacts
end_time: 1762304931026
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: a929877bac9d4c38868b65dd46cc974d
run_name: sched_boost_seed222_2025-11-04_19-48-43_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762301971306
status: 3
tags: []
user_id: kn
