artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/960847033820624533/2c83d3efac0340d29e0ee60edc0b3763/artifacts
end_time: null
entry_point_name: ''
experiment_id: '960847033820624533'
lifecycle_stage: active
run_id: 2c83d3efac0340d29e0ee60edc0b3763
run_name: sched_boost_lr035_seed1337_2025-11-11_09-02-41_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1762893814765
status: 1
tags: []
user_id: kn
