artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478/429b57d8f06f4d24a4e6f5a2c228ad6c/artifacts
end_time: 1765887753989
entry_point_name: ''
experiment_id: '994680267604837478'
lifecycle_stage: active
run_id: 429b57d8f06f4d24a4e6f5a2c228ad6c
run_name: sched_boost_lr035_lean_seed222_2025-12-16_11-44-37_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765887458022
status: 3
tags: []
user_id: vscode
