artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/ce95ea93f7f846e3b11e06fcbdfe3943/artifacts
end_time: 1764982409505
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: ce95ea93f7f846e3b11e06fcbdfe3943
run_name: large_batch_sched_boost_lean_seed222_2025-12-06_00-30-57_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764982305330
status: 3
tags: []
user_id: vscode
