artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/d31ae5db86f4486dba5bda2e864e9c02/artifacts
end_time: 1765039180789
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: d31ae5db86f4486dba5bda2e864e9c02
run_name: polish_seed101_2025-12-06_15-03-20
source_name: ''
source_type: 4
source_version: ''
start_time: 1765033408726
status: 3
tags: []
user_id: vscode
