artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/db1c4a247ac14c06ac5fe4192994aeef/artifacts
end_time: 1765087809244
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: db1c4a247ac14c06ac5fe4192994aeef
run_name: polish_seed101_2025-12-06_15-03-20_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1765085032068
status: 3
tags: []
user_id: vscode
