artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/9b29b83e4ab84ae69e933abf8a2c9ade/artifacts
end_time: 1766171844950
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: 9b29b83e4ab84ae69e933abf8a2c9ade
run_name: polish_seed888_2025-12-19_18-47-31
source_name: ''
source_type: 4
source_version: ''
start_time: 1766170061098
status: 3
tags: []
user_id: vscode
