artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522/2fcb51446d6a4dc5a0cfb58386c7d78d/artifacts
end_time: 1763069394811
entry_point_name: ''
experiment_id: '195331767355654522'
lifecycle_stage: active
run_id: 2fcb51446d6a4dc5a0cfb58386c7d78d
run_name: sched_boost_seed222_2025-11-13_20-44-30
source_name: ''
source_type: 4
source_version: ''
start_time: 1763066689617
status: 3
tags: []
user_id: kn
