artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/bc32f41b152e4377b5a71fb658f5ef14/artifacts
end_time: 1764982077990
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: bc32f41b152e4377b5a71fb658f5ef14
run_name: large_batch_sched_boost_lean_seed222_2025-12-06_00-30-57_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1764981842068
status: 3
tags: []
user_id: vscode
