artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/f9e33f2d49fc401ea31aa8dec123b673/artifacts
end_time: 1764078610561
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: f9e33f2d49fc401ea31aa8dec123b673
run_name: sched_boost_seed222_2025-11-25_09-32-00_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764077993161
status: 3
tags: []
user_id: vscode
