artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/8c8b348f5cec47f48da0a8df28b473c8/artifacts
end_time: 1762114999127
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 8c8b348f5cec47f48da0a8df28b473c8
run_name: sched_boost_seed222_2025-11-02_10-38-47_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1762113914292
status: 3
tags: []
user_id: kn
