artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478
creation_time: 1765884471745
experiment_id: '994680267604837478'
last_update_time: 1765884471745
lifecycle_stage: active
name: dynamic_topoqa
