artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932/1e96cadb45094b31bed16f442057f1d4/artifacts
end_time: 1764633241779
entry_point_name: ''
experiment_id: '553929320275185932'
lifecycle_stage: active
run_id: 1e96cadb45094b31bed16f442057f1d4
run_name: polish_lr_low_seed555_2025-12-01_22-40-37
source_name: ''
source_type: 4
source_version: ''
start_time: 1764628846270
status: 3
tags: []
user_id: vscode
