artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/1b268ad50fdc4fa0807dc876ebce1239/artifacts
end_time: 1766176055866
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: 1b268ad50fdc4fa0807dc876ebce1239
run_name: polish_lr_low_seed888_2025-12-19_19-17-25
source_name: ''
source_type: 4
source_version: ''
start_time: 1766171854599
status: 3
tags: []
user_id: vscode
