artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/175e652ec4ea4858bd3956ec007c53dc/artifacts
end_time: null
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: 175e652ec4ea4858bd3956ec007c53dc
run_name: sched_boost_seed222_2025-11-24_10-01-18
source_name: ''
source_type: 4
source_version: ''
start_time: 1763978519198
status: 1
tags: []
user_id: vscode
