artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/54857e0d78764a05a8de9e7ef6823a5f/artifacts
end_time: 1763919848132
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: 54857e0d78764a05a8de9e7ef6823a5f
run_name: large_batch_sched_boost_seed222_2025-11-23_17-27-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1763918912714
status: 3
tags: []
user_id: vscode
