artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/811543d163d043cdb3619cf0b2b536b4/artifacts
end_time: 1765476362049
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: 811543d163d043cdb3619cf0b2b536b4
run_name: large_batch_sched_boost_lean_seed222_2025-12-11_17-46-16_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1765476249674
status: 3
tags: []
user_id: vscode
