artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223/22ec0d89ed344e6884dba0d426298cd2/artifacts
end_time: 1765927100884
entry_point_name: ''
experiment_id: '578842538229463223'
lifecycle_stage: active
run_id: 22ec0d89ed344e6884dba0d426298cd2
run_name: polish_lr_low_seed101_2025-12-16_22-41-21
source_name: ''
source_type: 4
source_version: ''
start_time: 1765924887937
status: 3
tags: []
user_id: vscode
