artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/3c8dea90d7ca44eeb815cca81e841a2c/artifacts
end_time: 1764466797093
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: 3c8dea90d7ca44eeb815cca81e841a2c
run_name: sched_boost_lr035_lean_seed222_2025-11-29_23-48-40_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764466015925
status: 3
tags: []
user_id: vscode
