artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/2caab172c83145b38d5f166aa3fb3e60/artifacts
end_time: 1766159717052
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: 2caab172c83145b38d5f166aa3fb3e60
run_name: polish_seed101_2025-12-19_15-03-18
source_name: ''
source_type: 4
source_version: ''
start_time: 1766156609076
status: 3
tags: []
user_id: vscode
