artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/d349fd7cacf54a49a7b1d32e53820a10/artifacts
end_time: 1764518789382
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: d349fd7cacf54a49a7b1d32e53820a10
run_name: latest_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764517047453
status: 3
tags: []
user_id: vscode
