artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/757735313826032059/2e4c552fcbcc4ffa9bbf656b910766f0/artifacts
end_time: 1763802252700
entry_point_name: ''
experiment_id: '757735313826032059'
lifecycle_stage: active
run_id: 2e4c552fcbcc4ffa9bbf656b910766f0
run_name: sched_boost_seed222_2025-11-22_08-30-45
source_name: ''
source_type: 4
source_version: ''
start_time: 1763800267450
status: 3
tags: []
user_id: vscode
