artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/9ff8df9bcdc8445a82f6a3079773ccba/artifacts
end_time: 1765277170587
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: 9ff8df9bcdc8445a82f6a3079773ccba
run_name: polish_lr_low_seed555_2025-12-09_10-15-47
source_name: ''
source_type: 4
source_version: ''
start_time: 1765275352583
status: 3
tags: []
user_id: vscode
