artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/f24f5cc915bd4bbbafeb7b98f9b301ec/artifacts
end_time: 1764835210654
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: f24f5cc915bd4bbbafeb7b98f9b301ec
run_name: sched_boost_lean_seed222_2025-12-04_07-59-09
source_name: ''
source_type: 4
source_version: ''
start_time: 1764835156917
status: 3
tags: []
user_id: vscode
