artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/7c2dc75bbd5b475cae640cdcea3517f9/artifacts
end_time: 1763944678322
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: 7c2dc75bbd5b475cae640cdcea3517f9
run_name: polish_seed888_2025-11-23_23-08-25
source_name: ''
source_type: 4
source_version: ''
start_time: 1763939342920
status: 3
tags: []
user_id: vscode
