artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165
creation_time: 1766142326656
experiment_id: '581198018460776165'
last_update_time: 1766142326656
lifecycle_stage: active
name: dynamic_topoqa
