artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/0a4c9720f07d4de3b664b877c9401127/artifacts
end_time: 1764362355326
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 0a4c9720f07d4de3b664b877c9401127
run_name: latest_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1764360405242
status: 3
tags: []
user_id: vscode
