artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/f1e0aa8896ab4d91be4d45628cc283b5/artifacts
end_time: 1762307314937
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: f1e0aa8896ab4d91be4d45628cc283b5
run_name: sched_boost_seed222_2025-11-04_19-48-43_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762304946546
status: 3
tags: []
user_id: kn
