artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223/5ef53115d0da49988fcd1fc4f94c208c/artifacts
end_time: 1765937014855
entry_point_name: ''
experiment_id: '578842538229463223'
lifecycle_stage: active
run_id: 5ef53115d0da49988fcd1fc4f94c208c
run_name: polish_seed888_2025-12-17_00-41-38_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765936530274
status: 3
tags: []
user_id: vscode
