artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/dce04facc96049e1b52b1a60cfba4a17/artifacts
end_time: 1764295206662
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: dce04facc96049e1b52b1a60cfba4a17
run_name: sched_boost_lr035_seed1337_2025-11-28_01-11-05
source_name: ''
source_type: 4
source_version: ''
start_time: 1764292277727
status: 3
tags: []
user_id: vscode
