artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974/9b02a48adc334f0b8b4c375c7aa2ec9c/artifacts
end_time: 1762685997789
entry_point_name: ''
experiment_id: '278908513362295974'
lifecycle_stage: active
run_id: 9b02a48adc334f0b8b4c375c7aa2ec9c
run_name: large_batch_sched_boost_seed1337_2025-11-09_10-48-07
source_name: ''
source_type: 4
source_version: ''
start_time: 1762685306345
status: 3
tags: []
user_id: kn
