artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/6591e43b6bf64ee2a00cd85ccc447d2d/artifacts
end_time: 1762111955270
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 6591e43b6bf64ee2a00cd85ccc447d2d
run_name: sched_boost_seed222_2025-11-02_19-22-33
source_name: ''
source_type: 4
source_version: ''
start_time: 1762111368041
status: 4
tags: []
user_id: kn
