artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/087ec3720d1a414fa325add68acebba9/artifacts
end_time: 1763923464391
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: 087ec3720d1a414fa325add68acebba9
run_name: sched_boost_lr035_seed777_2025-11-23_16-27-32_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1763922798398
status: 3
tags: []
user_id: vscode
