artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/20d611a0d0a047e1adf7af2deccb43b1/artifacts
end_time: 1764099139324
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 20d611a0d0a047e1adf7af2deccb43b1
run_name: polish_seed888_2025-11-25_17-17-08_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764098557658
status: 3
tags: []
user_id: vscode
