artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/5380cbae6bb2466dab2d262408ea40ae/artifacts
end_time: 1766143370136
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: 5380cbae6bb2466dab2d262408ea40ae
run_name: sched_boost_lean_seed222_2025-12-19_11-05-17
source_name: ''
source_type: 4
source_version: ''
start_time: 1766142326693
status: 3
tags: []
user_id: vscode
