accelerator: cpu
accumulate_grad_batches: 16
attention_head: 8
batch_size: 24
devices: 1
early_stopping_patience: 45
graph_dir: ../../graph_builder2/output/ARM/apparent_fixed_z_graph_builder2/graph_data
learning_rate: 0.005
lr_scheduler_factor: 0.2
lr_scheduler_patience: 6
num_epochs: 260
num_workers: 0
pooling_type: mean
precision: 32
save_dir: ./training_runs
seed: 1337
train_label_file: ./train.csv
val_label_file: ./val.csv
