artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/dbaa99064bc64ccab19f62f5da4f3353/artifacts
end_time: 1763958866907
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: dbaa99064bc64ccab19f62f5da4f3353
run_name: latest_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1763957086372
status: 3
tags: []
user_id: vscode
