artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/13189796961f4a0fbd6f32b045fc0ccf/artifacts
end_time: null
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: 13189796961f4a0fbd6f32b045fc0ccf
run_name: training_run_2025-11-08_08-09-45
source_name: ''
source_type: 4
source_version: ''
start_time: 1762589405802
status: 1
tags: []
user_id: kn
