artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/eb7b06bc0e8e47dd8657624840aead2a/artifacts
end_time: 1763060490119
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: eb7b06bc0e8e47dd8657624840aead2a
run_name: sched_boost_lr035_seed222_2025-11-13_10-10-08_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1763058862443
status: 3
tags: []
user_id: kn
