artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/508224ca01e34bd1a7902bc72abe950c/artifacts
end_time: 1765531857185
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: 508224ca01e34bd1a7902bc72abe950c
run_name: sched_boost_lean_seed222_2025-12-12_08-43-08_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1765531843310
status: 3
tags: []
user_id: vscode
