artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/983626403599653281
creation_time: 1762385242570
experiment_id: '983626403599653281'
last_update_time: 1762385242570
lifecycle_stage: active
name: dynamic_topoqa
