artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/9727fd8012e340f58dbd2d85c9f7addf/artifacts
end_time: 1764091028112
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 9727fd8012e340f58dbd2d85c9f7addf
run_name: polish_lr_low_seed555_2025-11-25_16-31-17
source_name: ''
source_type: 4
source_version: ''
start_time: 1764088309657
status: 3
tags: []
user_id: vscode
