artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/50081be362c44509822ee30872e6fbd5/artifacts
end_time: 1762278493337
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: 50081be362c44509822ee30872e6fbd5
run_name: seed222_tiny_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1762276108565
status: 3
tags: []
user_id: kn
