artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478/ff33df28bcc84475a7e564be9250abc2/artifacts
end_time: 1765887453159
entry_point_name: ''
experiment_id: '994680267604837478'
lifecycle_stage: active
run_id: ff33df28bcc84475a7e564be9250abc2
run_name: large_batch_sched_boost_lean_seed222_2025-12-16_12-02-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1765886581454
status: 3
tags: []
user_id: vscode
