artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/72e7c1d91db948cd8416b1c2b58373b9/artifacts
end_time: 1765476244051
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: 72e7c1d91db948cd8416b1c2b58373b9
run_name: large_batch_sched_boost_lean_seed222_2025-12-11_17-46-16_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765475998060
status: 3
tags: []
user_id: vscode
