artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/af87648bd3504df1bccaaf0b587f102f/artifacts
end_time: 1764279784463
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: af87648bd3504df1bccaaf0b587f102f
run_name: sched_boost_seed222_2025-11-27_20-54-45
source_name: ''
source_type: 4
source_version: ''
start_time: 1764276898189
status: 3
tags: []
user_id: vscode
