artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/67f5e8c63ca14acf9b7d2b71d0f189fb/artifacts
end_time: 1764311900668
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 67f5e8c63ca14acf9b7d2b71d0f189fb
run_name: sched_boost_lr035_seed222_2025-11-27_23-38-29_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764308682648
status: 3
tags: []
user_id: vscode
