artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/0f92f2afcd08423494f77ef9f2701692/artifacts
end_time: null
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: 0f92f2afcd08423494f77ef9f2701692
run_name: bundlee_cert_smoke
source_name: ''
source_type: 4
source_version: ''
start_time: 1762382577684
status: 1
tags: []
user_id: kn
