artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/368408924535291840/c0b4d9eac65b4e659f14c69c60e1a41e/artifacts
end_time: 1763132860522
entry_point_name: ''
experiment_id: '368408924535291840'
lifecycle_stage: active
run_id: c0b4d9eac65b4e659f14c69c60e1a41e
run_name: sched_boost_seed1337_2025-11-14_09-06-54_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1763131753901
status: 3
tags: []
user_id: kn
