artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/23df1f1dfa214e58b10cc4d61c0b9cef/artifacts
end_time: 1766111252869
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: 23df1f1dfa214e58b10cc4d61c0b9cef
run_name: polish_seed888_2025-12-19_01-54-12
source_name: ''
source_type: 4
source_version: ''
start_time: 1766109261661
status: 3
tags: []
user_id: vscode
