artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/181cdd76a40b45779160a363bffdda99/artifacts
end_time: 1765124536169
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: 181cdd76a40b45779160a363bffdda99
run_name: polish_lr_low_seed888_2025-12-07_15-33-36
source_name: ''
source_type: 4
source_version: ''
start_time: 1765121622555
status: 3
tags: []
user_id: vscode
