artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/a7279b6b388e4fd3861f1ae49c1e2d8b/artifacts
end_time: 1764835623040
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: a7279b6b388e4fd3861f1ae49c1e2d8b
run_name: sched_boost_lr035_lean_seed222_2025-12-04_08-00-11
source_name: ''
source_type: 4
source_version: ''
start_time: 1764835216035
status: 3
tags: []
user_id: vscode
