artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478/f1c15ca6391b40f186b0a55e745ff0b1/artifacts
end_time: 1765895751791
entry_point_name: ''
experiment_id: '994680267604837478'
lifecycle_stage: active
run_id: f1c15ca6391b40f186b0a55e745ff0b1
run_name: polish_lr_low_seed101_2025-12-16_13-35-01
source_name: ''
source_type: 4
source_version: ''
start_time: 1765892106485
status: 3
tags: []
user_id: vscode
