artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/b51b4f5e9bad46ab940fa4acf2b04637/artifacts
end_time: null
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: b51b4f5e9bad46ab940fa4acf2b04637
run_name: seed222_bootstrap
source_name: ''
source_type: 4
source_version: ''
start_time: 1762268101636
status: 1
tags: []
user_id: kn
