artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/983626403599653281/b97ec95b7dfc4701ad03ba6523fb46d1/artifacts
end_time: null
entry_point_name: ''
experiment_id: '983626403599653281'
lifecycle_stage: active
run_id: b97ec95b7dfc4701ad03ba6523fb46d1
run_name: bundlei_runtime
source_name: ''
source_type: 4
source_version: ''
start_time: 1762429239660
status: 1
tags: []
user_id: kn
