artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/ef540329beb24cae8b43917a2209e0a7/artifacts
end_time: 1762118251853
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: ef540329beb24cae8b43917a2209e0a7
run_name: sched_boost_seed222_2025-11-02_10-38-47_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762116682435
status: 3
tags: []
user_id: kn
