artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478/68c10cfac7de430297f6fe71e97eabd8/artifacts
end_time: 1765897625991
entry_point_name: ''
experiment_id: '994680267604837478'
lifecycle_stage: active
run_id: 68c10cfac7de430297f6fe71e97eabd8
run_name: polish_seed555_2025-12-16_14-35-52
source_name: ''
source_type: 4
source_version: ''
start_time: 1765895757123
status: 3
tags: []
user_id: vscode
