artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/2df1e2bd03154ff1ae275a7938c5d40b/artifacts
end_time: 1764998664020
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: 2df1e2bd03154ff1ae275a7938c5d40b
run_name: polish_seed888_2025-12-06_03-54-28_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764998410125
status: 3
tags: []
user_id: vscode
