artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522/ed75bfcc17634d96a85b63ea339839ac/artifacts
end_time: 1763099168838
entry_point_name: ''
experiment_id: '195331767355654522'
lifecycle_stage: active
run_id: ed75bfcc17634d96a85b63ea339839ac
run_name: sched_boost_seed1337_2025-11-13_23-22-18_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1763097448692
status: 3
tags: []
user_id: kn
