artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/203034696812255868/efc1c7f5a43d492fb58bcccf2eb981fa/artifacts
end_time: 1762595041993
entry_point_name: ''
experiment_id: '203034696812255868'
lifecycle_stage: active
run_id: efc1c7f5a43d492fb58bcccf2eb981fa
run_name: sched_boost_seed222_2025-11-08_09-14-15
source_name: ''
source_type: 4
source_version: ''
start_time: 1762593272964
status: 3
tags: []
user_id: kn
