artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691/0d9b3a50e51549b994a71cca4b47d07f/artifacts
end_time: 1764704329185
entry_point_name: ''
experiment_id: '704094476654428691'
lifecycle_stage: active
run_id: 0d9b3a50e51549b994a71cca4b47d07f
run_name: large_batch_sched_boost_lean_seed222_2025-12-02_19-25-12
source_name: ''
source_type: 4
source_version: ''
start_time: 1764703518090
status: 3
tags: []
user_id: vscode
