artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/1e8b4c6e2a424da9bba969abe3f1f953/artifacts
end_time: 1765121616353
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: 1e8b4c6e2a424da9bba969abe3f1f953
run_name: polish_seed888_2025-12-07_15-07-00
source_name: ''
source_type: 4
source_version: ''
start_time: 1765120026003
status: 3
tags: []
user_id: vscode
