artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949
creation_time: 1765472749761
experiment_id: '686301252057198949'
last_update_time: 1765472749761
lifecycle_stage: active
name: dynamic_topoqa
