artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/9596320f76a249faab4d417f99acdb9e/artifacts
end_time: 1765029149470
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: 9596320f76a249faab4d417f99acdb9e
run_name: sched_boost_lr035_lean_seed222_2025-12-06_13-27-34
source_name: ''
source_type: 4
source_version: ''
start_time: 1765027662180
status: 3
tags: []
user_id: vscode
