artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/757735313826032059/7f42b91c048e4ac2a59eceec984e2c63/artifacts
end_time: 1763812903163
entry_point_name: ''
experiment_id: '757735313826032059'
lifecycle_stage: active
run_id: 7f42b91c048e4ac2a59eceec984e2c63
run_name: large_batch_sched_boost_seed777_2025-11-22_11-43-11
source_name: ''
source_type: 4
source_version: ''
start_time: 1763811820859
status: 3
tags: []
user_id: vscode
