artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/7c1b77c52adf4b8785de49121010a6ac/artifacts
end_time: null
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: 7c1b77c52adf4b8785de49121010a6ac
run_name: sched_boost_seed222_fastdev_2025-11-04_14-38-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1762267151309
status: 1
tags: []
user_id: kn
