artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/74d2cee0acc140f89ca3d6ccc164b868/artifacts
end_time: 1762119794475
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 74d2cee0acc140f89ca3d6ccc164b868
run_name: sched_boost_seed222_2025-11-02_10-38-47_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762118265249
status: 3
tags: []
user_id: kn
