artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613
creation_time: 1762075127715
experiment_id: '602587911472957613'
last_update_time: 1762075127715
lifecycle_stage: active
name: dynamic_topoqa
