artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/263834183455537235
creation_time: 1763845878339
experiment_id: '263834183455537235'
last_update_time: 1763845878339
lifecycle_stage: active
name: dynamic_topoqa
