artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538
creation_time: 1764835156881
experiment_id: '572946763623760538'
last_update_time: 1764835156881
lifecycle_stage: active
name: dynamic_topoqa
