artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/3523f02cda63473fbde973e7bbbc00cc/artifacts
end_time: 1765490427138
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: 3523f02cda63473fbde973e7bbbc00cc
run_name: polish_seed888_2025-12-11_21-29-03
source_name: ''
source_type: 4
source_version: ''
start_time: 1765488550603
status: 3
tags: []
user_id: vscode
