artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/52505bbcae064bd0a5cbe7f32f9183fa/artifacts
end_time: 1764067675766
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 52505bbcae064bd0a5cbe7f32f9183fa
run_name: sched_boost_seed1337_2025-11-25_10-27-23
source_name: ''
source_type: 4
source_version: ''
start_time: 1764066483981
status: 3
tags: []
user_id: vscode
