artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/4c7ad076977445db88aaff0e1d4f6e23/artifacts
end_time: 1765531800240
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: 4c7ad076977445db88aaff0e1d4f6e23
run_name: sched_boost_lean_seed222_2025-12-12_08-43-08_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765531505878
status: 3
tags: []
user_id: vscode
