artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974/a81cdbf87a864b6680d7f99360bfc54b/artifacts
end_time: 1762691151330
entry_point_name: ''
experiment_id: '278908513362295974'
lifecycle_stage: active
run_id: a81cdbf87a864b6680d7f99360bfc54b
run_name: sched_boost_seed777_2025-11-09_08-46-53_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762690679824
status: 3
tags: []
user_id: kn
