artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932/c16e1884deb34f11a3be99202878f3ca/artifacts
end_time: 1764621723967
entry_point_name: ''
experiment_id: '553929320275185932'
lifecycle_stage: active
run_id: c16e1884deb34f11a3be99202878f3ca
run_name: polish_lr_low_seed101_2025-12-01_18-40-33
source_name: ''
source_type: 4
source_version: ''
start_time: 1764614442021
status: 3
tags: []
user_id: vscode
