artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/6a55f3cc5696429083defaab8fe0b113/artifacts
end_time: 1764980142250
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: 6a55f3cc5696429083defaab8fe0b113
run_name: sched_boost_lean_seed222_2025-12-05_23-53-31
source_name: ''
source_type: 4
source_version: ''
start_time: 1764978818059
status: 3
tags: []
user_id: vscode
