artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/830446690413640518/1ee5cbe76b624651be70f319e398cad2/artifacts
end_time: 1763285300958
entry_point_name: ''
experiment_id: '830446690413640518'
lifecycle_stage: active
run_id: 1ee5cbe76b624651be70f319e398cad2
run_name: sched_boost_seed1337_2025-11-16_08-53-55
source_name: ''
source_type: 4
source_version: ''
start_time: 1763283264791
status: 3
tags: []
user_id: kn
