artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/bff5c3904cf54c478956508c2bb43f84/artifacts
end_time: 1764836002121
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: bff5c3904cf54c478956508c2bb43f84
run_name: large_batch_sched_boost_lean_seed222_2025-12-04_08-07-03
source_name: ''
source_type: 4
source_version: ''
start_time: 1764835634273
status: 3
tags: []
user_id: vscode
