artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/260951b2dcd94552bdb666f59e27a8cb/artifacts
end_time: 1764364139271
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 260951b2dcd94552bdb666f59e27a8cb
run_name: latest_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764362368797
status: 3
tags: []
user_id: vscode
