artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829/0cc8f7aecbae496aa4a6cbdfb12a8236/artifacts
end_time: 1762721678287
entry_point_name: ''
experiment_id: '157436571815778829'
lifecycle_stage: active
run_id: 0cc8f7aecbae496aa4a6cbdfb12a8236
run_name: large_batch_sched_boost_seed1337_2025-11-09_19-54-28_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762720822357
status: 3
tags: []
user_id: kn
