accelerator: cpu
accumulate_grad_batches: 16
attention_head: 8
batch_size: 16
devices: 1
early_stopping_patience: 20
graph_dir: ../../graph_builder2/output/ARM/apparent_fixed_z_graph_builder2/graph_data
learning_rate: 0.001
lr_scheduler_factor: 0.2
lr_scheduler_patience: 4
num_epochs: 320
num_workers: 0
pooling_type: mean
precision: 32
save_dir: ./training_runs
seed: 222
train_label_file: ./train.csv
val_label_file: ./val.csv
