artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/f71b88c5e9a04f7696f604c2fb436c2d/artifacts
end_time: 1762552570624
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: f71b88c5e9a04f7696f604c2fb436c2d
run_name: large_batch_sched_boost_seed222_2025-11-07_21-00-06_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762551949112
status: 3
tags: []
user_id: kn
