artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/4bfebf53ae474a08a48e128b9424fa2c/artifacts
end_time: 1765549159782
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: 4bfebf53ae474a08a48e128b9424fa2c
run_name: polish_lr_low_seed555_2025-12-12_11-38-01_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1765549059184
status: 3
tags: []
user_id: vscode
