artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/85f61fb90d6447d3ab3879ddb6e6ace6/artifacts
end_time: 1764070176558
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 85f61fb90d6447d3ab3879ddb6e6ace6
run_name: sched_boost_lr035_seed777_2025-11-25_11-07-02
source_name: ''
source_type: 4
source_version: ''
start_time: 1764068863851
status: 3
tags: []
user_id: vscode
