artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522
creation_time: 1763066689571
experiment_id: '195331767355654522'
last_update_time: 1763066689571
lifecycle_stage: active
name: dynamic_topoqa
