artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/e5db7ee4fdd84d75877943dda4f579dc/artifacts
end_time: 1763033748753
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: e5db7ee4fdd84d75877943dda4f579dc
run_name: sched_boost_lr035_seed222_2025-11-13_10-10-08
source_name: ''
source_type: 4
source_version: ''
start_time: 1763028626231
status: 3
tags: []
user_id: kn
