artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/70defea54c0341bca6f4b066ed830fe7/artifacts
end_time: 1762360660936
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: 70defea54c0341bca6f4b066ed830fe7
run_name: large_batch_sched_boost_seed222_2025-11-05_15-20-16
source_name: ''
source_type: 4
source_version: ''
start_time: 1762356030616
status: 3
tags: []
user_id: kn
