artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/a153ff8b6d2f4c5a906dff452233eebe/artifacts
end_time: 1762547646413
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: a153ff8b6d2f4c5a906dff452233eebe
run_name: sched_boost_seed222_2025-11-07_20-05-17
source_name: ''
source_type: 4
source_version: ''
start_time: 1762545934676
status: 3
tags: []
user_id: kn
