artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829/aceeca8c2212496ea16dbbb69c4d2ec3/artifacts
end_time: 1762707415521
entry_point_name: ''
experiment_id: '157436571815778829'
lifecycle_stage: active
run_id: aceeca8c2212496ea16dbbb69c4d2ec3
run_name: sched_boost_lr035_seed222_2025-11-09_16-28-49
source_name: ''
source_type: 4
source_version: ''
start_time: 1762705753452
status: 3
tags: []
user_id: kn
