artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/7c9e23c9acf1486ca89ab4ff41c7cece/artifacts
end_time: 1762583869185
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: 7c9e23c9acf1486ca89ab4ff41c7cece
run_name: sched_boost_lr035_seed1337_2025-11-08_03-24-45_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1762583113580
status: 3
tags: []
user_id: kn
