artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/8ae9e587be264ff4893da4d8a3ef0714/artifacts
end_time: 1765031694048
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: 8ae9e587be264ff4893da4d8a3ef0714
run_name: sched_boost_lean_seed222_2025-12-06_12-42-55_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1765031070376
status: 3
tags: []
user_id: vscode
