artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271
creation_time: 1764978818019
experiment_id: '133858506419254271'
last_update_time: 1764978818019
lifecycle_stage: active
name: dynamic_topoqa
