artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/c5ec9e2b84e74b3da670067adc2c83f6/artifacts
end_time: 1764843653959
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: c5ec9e2b84e74b3da670067adc2c83f6
run_name: polish_lr_low_seed888_2025-12-04_10-16-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1764843415659
status: 3
tags: []
user_id: vscode
