artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223/6a712aa390d34dfc80337c91b2a0e4f0/artifacts
end_time: 1765923219672
entry_point_name: ''
experiment_id: '578842538229463223'
lifecycle_stage: active
run_id: 6a712aa390d34dfc80337c91b2a0e4f0
run_name: large_batch_sched_boost_lean_seed222_2025-12-16_21-51-52_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1765923144520
status: 3
tags: []
user_id: vscode
