artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/2d55778251e94e618f9a7f40cbdc5b1c/artifacts
end_time: 1764522308735
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: 2d55778251e94e618f9a7f40cbdc5b1c
run_name: latest_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764520542470
status: 3
tags: []
user_id: vscode
