artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/ff41fd98eae14c6ea9a920f233db93e1/artifacts
end_time: 1763989025712
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: ff41fd98eae14c6ea9a920f233db93e1
run_name: sched_boost_lr035_seed1337_2025-11-24_12-24-37
source_name: ''
source_type: 4
source_version: ''
start_time: 1763987117375
status: 3
tags: []
user_id: vscode
