artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223/e1e6c18b26ab463da52396c9eb7b9f0b/artifacts
end_time: 1765923060432
entry_point_name: ''
experiment_id: '578842538229463223'
lifecycle_stage: active
run_id: e1e6c18b26ab463da52396c9eb7b9f0b
run_name: large_batch_sched_boost_lean_seed222_2025-12-16_21-51-52_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1765922984968
status: 3
tags: []
user_id: vscode
