artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/368408924535291840/a5a8b43d3bf946fa8d0c855896737b55/artifacts
end_time: null
entry_point_name: ''
experiment_id: '368408924535291840'
lifecycle_stage: active
run_id: a5a8b43d3bf946fa8d0c855896737b55
run_name: sched_boost_seed777_2025-11-14_08-28-09
source_name: ''
source_type: 4
source_version: ''
start_time: 1763108911703
status: 1
tags: []
user_id: kn
