artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/2f8c893a2ef54a8f85e4433e92d243e5/artifacts
end_time: 1763045770154
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: 2f8c893a2ef54a8f85e4433e92d243e5
run_name: large_batch_sched_boost_seed222_2025-11-13_13-51-26
source_name: ''
source_type: 4
source_version: ''
start_time: 1763041903353
status: 3
tags: []
user_id: kn
