artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/61479ad7e22e402ab2752c5e95c4d1ff/artifacts
end_time: 1765047270313
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: 61479ad7e22e402ab2752c5e95c4d1ff
run_name: polish_lr_low_seed101_2025-12-06_16-39-41
source_name: ''
source_type: 4
source_version: ''
start_time: 1765039189438
status: 3
tags: []
user_id: vscode
