artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/30951b7693da4afd8c4a2e21bc3b770f/artifacts
end_time: 1764843916282
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: 30951b7693da4afd8c4a2e21bc3b770f
run_name: polish_seed555_2025-12-04_09-25-54_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764843836270
status: 3
tags: []
user_id: vscode
