edge:
  module: edge/edge_plus_pool_agg_lap_hybrid/v1  # alias: Legacy 11D Edge + 1382D {(hist + endpoint agg + pooled agg) from 172D laplacian_hybrid} = Edge 1393D (Lean) | Legacy 11D Edge + 2070D {(hist + endpoint agg + pooled agg + minmax) from laplacian_hybrid} = Edge 2081D (Heavy)
  alias: "Legacy 11D Edge + 2070D {(hist + endpoint agg + pooled agg + minmax) from laplacian_hybrid} = Edge 2081D (Heavy)"
  summary: "Legacy 11D histogram + hybrid pooled topo agg (PH+Lap 172D)."
  description: "Same aggregation as edge_plus_pool_agg_topo/v1, intended for use with topology/persistence_laplacian_hybrid/v1 (per-residue PH + Laplacian vectors, expected topo_dim\u2248172). Prepends the legacy 11D distance histogram, then applies balanced aggregation on endpoints and pooled neighbor means (concat, mean, abs-diff, optional norms/cosine); heavy variant adds per-dimension min/max. Deterministic edge ordering (src_idx, dst_idx, distance) preserved."
  params:
    distance_min: 0.0
    distance_max: 10.0
    scale_histogram: true
    include_norms: true
    include_cosine: true
    pool_k: 5  # number of nearest interface residues to pool per endpoint (default 5)
    include_minmax: true  # heavy variant only; adds per-dimension min/max blocks to endpoint and pooled agg
    variant: heavy  # lean or heavy
    jobs: 16
