artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/830446690413640518/fa8e53cb86ab43db86e4326c9d24f523/artifacts
end_time: 1763281229361
entry_point_name: ''
experiment_id: '830446690413640518'
lifecycle_stage: active
run_id: fa8e53cb86ab43db86e4326c9d24f523
run_name: sched_boost_seed222_2025-11-16_07-51-12
source_name: ''
source_type: 4
source_version: ''
start_time: 1763279502784
status: 3
tags: []
user_id: kn
