artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/55b5c5a02813450abb3f178c69db8ffd/artifacts
end_time: 1764997924158
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: 55b5c5a02813450abb3f178c69db8ffd
run_name: polish_lr_low_seed888_2025-12-06_04-22-28
source_name: ''
source_type: 4
source_version: ''
start_time: 1764994953127
status: 3
tags: []
user_id: vscode
