artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/5cad070b0e084082b792faf47ea2cc5b/artifacts
end_time: 1766089104947
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: 5cad070b0e084082b792faf47ea2cc5b
run_name: polish_seed101_2025-12-18_19-42-39
source_name: ''
source_type: 4
source_version: ''
start_time: 1766086965658
status: 3
tags: []
user_id: vscode
