artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/1b5f3a470eb444cfab8c21b43ecf0633/artifacts
end_time: 1763062069662
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: 1b5f3a470eb444cfab8c21b43ecf0633
run_name: sched_boost_lr035_seed222_2025-11-13_10-10-08_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1763060512388
status: 3
tags: []
user_id: kn
