artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/1d355188304e445fb4b7aa93b4fdf6a6/artifacts
end_time: 1765108073579
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: 1d355188304e445fb4b7aa93b4fdf6a6
run_name: sched_boost_lean_seed222_2025-12-07_11-30-22
source_name: ''
source_type: 4
source_version: ''
start_time: 1765107027684
status: 3
tags: []
user_id: vscode
