artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411
creation_time: 1764063161151
experiment_id: '465292636398478411'
last_update_time: 1764063161151
lifecycle_stage: active
name: dynamic_topoqa
