artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/0d58c1e00b1c41a0a3e421e20e3517a2/artifacts
end_time: 1764982189373
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: 0d58c1e00b1c41a0a3e421e20e3517a2
run_name: large_batch_sched_boost_lean_seed222_2025-12-06_00-30-57_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764982083430
status: 3
tags: []
user_id: vscode
