artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/06dcc8057a0a41b5903f76b59c30f075/artifacts
end_time: 1764981836625
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: 06dcc8057a0a41b5903f76b59c30f075
run_name: large_batch_sched_boost_lean_seed222_2025-12-06_00-30-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1764981062820
status: 3
tags: []
user_id: vscode
