artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609
creation_time: 1765107027649
experiment_id: '808112237968465609'
last_update_time: 1765107027649
lifecycle_stage: active
name: dynamic_topoqa
