artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/02c1dcbf17904406b4e7807ba32b2fb0/artifacts
end_time: 1764012480094
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: 02c1dcbf17904406b4e7807ba32b2fb0
run_name: polish_lr_low_seed888_2025-11-24_18-32-51
source_name: ''
source_type: 4
source_version: ''
start_time: 1764009212868
status: 3
tags: []
user_id: vscode
