artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/960847033820624533
creation_time: 1762798849551
experiment_id: '960847033820624533'
last_update_time: 1762798849551
lifecycle_stage: active
name: dynamic_topoqa
