artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/d75a31175cb7465f9cec3711f2e601ea/artifacts
end_time: 1765265704737
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: d75a31175cb7465f9cec3711f2e601ea
run_name: sched_boost_lr035_lean_seed222_2025-12-09_07-16-24
source_name: ''
source_type: 4
source_version: ''
start_time: 1765264589401
status: 3
tags: []
user_id: vscode
