artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/c294373c9c1e40bd87ce0ecdb7eaaf48/artifacts
end_time: 1763960435222
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: c294373c9c1e40bd87ce0ecdb7eaaf48
run_name: latest_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1763958907374
status: 3
tags: []
user_id: vscode
