artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/cab1b574dffa4bf2a3f39d7575f2ebea/artifacts
end_time: 1766086513140
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: cab1b574dffa4bf2a3f39d7575f2ebea
run_name: sched_boost_lr035_lean_seed222_2025-12-18_18-32-58_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1766085878445
status: 3
tags: []
user_id: vscode
