artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/1ee489f01ad449f3b4fceabd6577daba/artifacts
end_time: 1763916866388
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: 1ee489f01ad449f3b4fceabd6577daba
run_name: sched_boost_lr035_seed777_2025-11-23_16-27-32
source_name: ''
source_type: 4
source_version: ''
start_time: 1763915289668
status: 3
tags: []
user_id: vscode
