artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/6ef2ac7db030434ea6d227a67fc15e70/artifacts
end_time: 1764075949084
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 6ef2ac7db030434ea6d227a67fc15e70
run_name: large_batch_sched_boost_seed1337_2025-11-25_12-43-01
source_name: ''
source_type: 4
source_version: ''
start_time: 1764074621794
status: 3
tags: []
user_id: vscode
