artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/f44d33d42f2b42e7b7ce53fbd011db42/artifacts
end_time: 1764466004103
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: f44d33d42f2b42e7b7ce53fbd011db42
run_name: sched_boost_lr035_lean_seed222_2025-11-29_23-48-40_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764465216580
status: 3
tags: []
user_id: vscode
