artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/b3e85eb5cdd5460b88b710dcb1b9fb2f/artifacts
end_time: 1764074580891
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: b3e85eb5cdd5460b88b710dcb1b9fb2f
run_name: large_batch_sched_boost_seed777_2025-11-25_12-16-19
source_name: ''
source_type: 4
source_version: ''
start_time: 1764073020285
status: 3
tags: []
user_id: vscode
