artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/f8433ab1565e4c86b29dda1dd2c5b98d/artifacts
end_time: 1764099762546
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: f8433ab1565e4c86b29dda1dd2c5b98d
run_name: polish_seed888_2025-11-25_17-17-08_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764099171995
status: 3
tags: []
user_id: vscode
