artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478/29badf4f4c394333beaa717c33facbbb/artifacts
end_time: 1765902380347
entry_point_name: ''
experiment_id: '994680267604837478'
lifecycle_stage: active
run_id: 29badf4f4c394333beaa717c33facbbb
run_name: polish_seed888_2025-12-16_15-51-38
source_name: ''
source_type: 4
source_version: ''
start_time: 1765900302295
status: 3
tags: []
user_id: vscode
