artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/9c4cd787d8fd4cffb28ffa55853d0be2/artifacts
end_time: 1764002349550
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: 9c4cd787d8fd4cffb28ffa55853d0be2
run_name: polish_lr_low_seed101_2025-11-24_15-42-30
source_name: ''
source_type: 4
source_version: ''
start_time: 1763998988666
status: 3
tags: []
user_id: vscode
