artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/fd7b6f4be0054e3a9a45a3e932611ca3/artifacts
end_time: 1762112959446
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: fd7b6f4be0054e3a9a45a3e932611ca3
run_name: sched_boost_seed222_2025-11-02_10-38-47_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762112030746
status: 3
tags: []
user_id: kn
