artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/bee1da3e3a874f9280f159b713761f9f/artifacts
end_time: 1766179180339
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: bee1da3e3a874f9280f159b713761f9f
run_name: polish_lr_low_seed101_2025-12-19_15-55-17_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1766178322080
status: 3
tags: []
user_id: vscode
