artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/68b98d238fd047cd9f4e69d4321bfae5/artifacts
end_time: 1764068822406
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 68b98d238fd047cd9f4e69d4321bfae5
run_name: sched_boost_lr035_seed222_2025-11-25_10-47-56
source_name: ''
source_type: 4
source_version: ''
start_time: 1764067717139
status: 3
tags: []
user_id: vscode
