artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829/a822b5f481e345ecb567ba96fc5ed451/artifacts
end_time: 1762700436814
entry_point_name: ''
experiment_id: '157436571815778829'
lifecycle_stage: active
run_id: a822b5f481e345ecb567ba96fc5ed451
run_name: sched_boost_seed222_2025-11-09_14-12-20
source_name: ''
source_type: 4
source_version: ''
start_time: 1762697563318
status: 3
tags: []
user_id: kn
