artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/960847033820624533/f7eb3a4b6fe4482abbf8361f2a8ab52b/artifacts
end_time: 1762838204341
entry_point_name: ''
experiment_id: '960847033820624533'
lifecycle_stage: active
run_id: f7eb3a4b6fe4482abbf8361f2a8ab52b
run_name: sched_boost_seed777_2025-11-11_00-44-39
source_name: ''
source_type: 4
source_version: ''
start_time: 1762821909824
status: 3
tags: []
user_id: kn
