artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/87509b20ce234caa8e098eaf1716cd14/artifacts
end_time: 1765264584035
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: 87509b20ce234caa8e098eaf1716cd14
run_name: sched_boost_lean_seed222_2025-12-09_06-58-32
source_name: ''
source_type: 4
source_version: ''
start_time: 1765263520013
status: 3
tags: []
user_id: vscode
