artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/263834183455537235/e96a1cdf8ca74f0d924e53fcf9d0f770/artifacts
end_time: 1763855452571
entry_point_name: ''
experiment_id: '263834183455537235'
lifecycle_stage: active
run_id: e96a1cdf8ca74f0d924e53fcf9d0f770
run_name: large_batch_sched_boost_seed222_2025-11-22_23-21-03
source_name: ''
source_type: 4
source_version: ''
start_time: 1763853689978
status: 3
tags: []
user_id: vscode
