artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/6703ce33c0e94ca6a7b455f4f3688aca/artifacts
end_time: 1764349947746
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 6703ce33c0e94ca6a7b455f4f3688aca
run_name: polish_lr_low_seed555_2025-11-28_14-56-58
source_name: ''
source_type: 4
source_version: ''
start_time: 1764341832475
status: 3
tags: []
user_id: vscode
