artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974
creation_time: 1762676847980
experiment_id: '278908513362295974'
last_update_time: 1762676847980
lifecycle_stage: active
name: dynamic_topoqa
