artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/e83a0cd594d049f9a18226e0faa8fa3d/artifacts
end_time: 1764076568899
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: e83a0cd594d049f9a18226e0faa8fa3d
run_name: sched_boost_seed222_2025-11-25_09-32-00_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1764075991317
status: 3
tags: []
user_id: vscode
