artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/b3976aabfbd1474dbf4e293a61fc3fc7/artifacts
end_time: 1763955415438
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: b3976aabfbd1474dbf4e293a61fc3fc7
run_name: polish_lr_low_seed888_2025-11-24_00-37-58
source_name: ''
source_type: 4
source_version: ''
start_time: 1763944717108
status: 3
tags: []
user_id: vscode
