artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/983626403599653281/ea18f3035d1e44f086ee064a61c86af4/artifacts
end_time: null
entry_point_name: ''
experiment_id: '983626403599653281'
lifecycle_stage: active
run_id: ea18f3035d1e44f086ee064a61c86af4
run_name: bundlei_runtime
source_name: ''
source_type: 4
source_version: ''
start_time: 1762428646866
status: 1
tags: []
user_id: kn
