artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/0329f8c3a84e46b09c383757b0ce47fd/artifacts
end_time: 1765030327777
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: 0329f8c3a84e46b09c383757b0ce47fd
run_name: large_batch_sched_boost_lean_seed222_2025-12-06_13-52-30
source_name: ''
source_type: 4
source_version: ''
start_time: 1765029157876
status: 3
tags: []
user_id: vscode
