artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/ac1a81d77b2a47e6958e334d1de566f8/artifacts
end_time: 1765474070595
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: ac1a81d77b2a47e6958e334d1de566f8
run_name: sched_boost_lean_seed222_2025-12-11_17-05-42
source_name: ''
source_type: 4
source_version: ''
start_time: 1765472749807
status: 3
tags: []
user_id: vscode
