artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/f5afd42f0c554b4e9429ad0dad4de2e7/artifacts
end_time: 1764313400935
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: f5afd42f0c554b4e9429ad0dad4de2e7
run_name: sched_boost_lr035_seed222_2025-11-27_23-38-29_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764311913367
status: 3
tags: []
user_id: vscode
