artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/b6ed7084e68842e48eed99e4c129f4ee/artifacts
end_time: 1765539480669
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: b6ed7084e68842e48eed99e4c129f4ee
run_name: polish_seed555_2025-12-12_11-11-44
source_name: ''
source_type: 4
source_version: ''
start_time: 1765537911854
status: 3
tags: []
user_id: vscode
