artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/ca1d02a5e38d47d1ab0acc6cca7b7c5c/artifacts
end_time: 1763910614408
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: ca1d02a5e38d47d1ab0acc6cca7b7c5c
run_name: sched_boost_seed222_2025-11-23_14-35-34
source_name: ''
source_type: 4
source_version: ''
start_time: 1763908571390
status: 3
tags: []
user_id: vscode
