artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821
creation_time: 1765528994983
experiment_id: '843924752530628821'
last_update_time: 1765528994983
lifecycle_stage: active
name: dynamic_topoqa
