artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829/ed86a067f3ae4835b276dc6f5aef7764/artifacts
end_time: 1762723307032
entry_point_name: ''
experiment_id: '157436571815778829'
lifecycle_stage: active
run_id: ed86a067f3ae4835b276dc6f5aef7764
run_name: large_batch_sched_boost_seed1337_2025-11-09_19-54-28_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1762722614519
status: 3
tags: []
user_id: kn
