artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/f21bbbad0ca34c6aba09c14bdbdca255/artifacts
end_time: 1764006250575
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: f21bbbad0ca34c6aba09c14bdbdca255
run_name: polish_lr_low_seed555_2025-11-24_17-03-15
source_name: ''
source_type: 4
source_version: ''
start_time: 1764003835825
status: 3
tags: []
user_id: vscode
