artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691/327b5b239af44796a7f5335d7ede2fc8/artifacts
end_time: 1764704602924
entry_point_name: ''
experiment_id: '704094476654428691'
lifecycle_stage: active
run_id: 327b5b239af44796a7f5335d7ede2fc8
run_name: large_batch_sched_boost_lean_seed222_2025-12-02_19-25-12_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764704589158
status: 3
tags: []
user_id: vscode
