artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/e63234c5dbd3408ebe076769e4cef9d1/artifacts
end_time: 1762109988716
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: e63234c5dbd3408ebe076769e4cef9d1
run_name: large_batch_sched_boost_seed1337_2025-11-02_18-35-18
source_name: ''
source_type: 4
source_version: ''
start_time: 1762108532869
status: 3
tags: []
user_id: kn
