artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522/5966a66cdbea44fcbf428d34b0c55549/artifacts
end_time: 1763101528632
entry_point_name: ''
experiment_id: '195331767355654522'
lifecycle_stage: active
run_id: 5966a66cdbea44fcbf428d34b0c55549
run_name: sched_boost_seed1337_2025-11-13_23-22-18_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1763100372131
status: 3
tags: []
user_id: kn
