artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/0c1eae2ce5a0412d8604e7efa5230ad1/artifacts
end_time: 1762120805010
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 0c1eae2ce5a0412d8604e7efa5230ad1
run_name: sched_boost_seed222_2025-11-02_10-38-47_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1762119807863
status: 3
tags: []
user_id: kn
