artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/536467477892488150
creation_time: 1763137953496
experiment_id: '536467477892488150'
last_update_time: 1763137953496
lifecycle_stage: active
name: dynamic_topoqa
