artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/29d25d46fca64bdbbd7306099f2c9b40/artifacts
end_time: 1764502897064
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: 29d25d46fca64bdbbd7306099f2c9b40
run_name: polish_lr_low_seed555_2025-11-30_08-34-33
source_name: ''
source_type: 4
source_version: ''
start_time: 1764491684358
status: 3
tags: []
user_id: vscode
