artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/536467477892488150/22ee4c934a874ca1acf3f54e41f8dade/artifacts
end_time: 1763164900408
entry_point_name: ''
experiment_id: '536467477892488150'
lifecycle_stage: active
run_id: 22ee4c934a874ca1acf3f54e41f8dade
run_name: large_batch_sched_boost_seed1337_2025-11-14_23-55-07
source_name: ''
source_type: 4
source_version: ''
start_time: 1763164540929
status: 4
tags: []
user_id: kn
