artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829/1015fb93e7d0488e980661ada84ccf6a/artifacts
end_time: 1762722589520
entry_point_name: ''
experiment_id: '157436571815778829'
lifecycle_stage: active
run_id: 1015fb93e7d0488e980661ada84ccf6a
run_name: large_batch_sched_boost_seed1337_2025-11-09_19-54-28_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762721702960
status: 3
tags: []
user_id: kn
