artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/203034696812255868/f8232db83d754f27af60f976e7cb31f9/artifacts
end_time: 1762616480553
entry_point_name: ''
experiment_id: '203034696812255868'
lifecycle_stage: active
run_id: f8232db83d754f27af60f976e7cb31f9
run_name: large_batch_sched_boost_seed1337_2025-11-08_15-15-29
source_name: ''
source_type: 4
source_version: ''
start_time: 1762614950159
status: 3
tags: []
user_id: kn
