artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/4c823f3dee094616a5f1381fff80ac08/artifacts
end_time: 1763050961263
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: 4c823f3dee094616a5f1381fff80ac08
run_name: large_batch_sched_boost_seed777_2025-11-13_14-56-10
source_name: ''
source_type: 4
source_version: ''
start_time: 1763045793541
status: 3
tags: []
user_id: kn
