artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/4ed43be21cb14d729de85a6ce4a88f17/artifacts
end_time: 1763939304742
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: 4ed43be21cb14d729de85a6ce4a88f17
run_name: polish_lr_low_seed555_2025-11-23_22-30-36
source_name: ''
source_type: 4
source_version: ''
start_time: 1763937074761
status: 3
tags: []
user_id: vscode
