artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/1e43f5eaa5e34c188917dfa0fc42c5d4/artifacts
end_time: 1762076197977
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 1e43f5eaa5e34c188917dfa0fc42c5d4
run_name: sched_boost_seed222_2025-11-01_14-19-18_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762075127763
status: 3
tags: []
user_id: kn
