artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/bb7539bb6987424e8a360f6fee591cc4/artifacts
end_time: 1765108751347
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: bb7539bb6987424e8a360f6fee591cc4
run_name: sched_boost_lr035_lean_seed222_2025-12-07_11-47-54
source_name: ''
source_type: 4
source_version: ''
start_time: 1765108079725
status: 3
tags: []
user_id: vscode
