artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/81b35efb0adf4965987c001370c602d5/artifacts
end_time: 1764015865974
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: 81b35efb0adf4965987c001370c602d5
run_name: latest_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764014053154
status: 3
tags: []
user_id: vscode
