artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062
creation_time: 1764455925832
experiment_id: '688850596195161062'
last_update_time: 1764455925832
lifecycle_stage: active
name: dynamic_topoqa
