artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/2ebc9f66651241b2a7ce8f7bf15387d4/artifacts
end_time: 1762273501698
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: 2ebc9f66651241b2a7ce8f7bf15387d4
run_name: seed222_tiny_finetune_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762268490971
status: 3
tags: []
user_id: kn
