artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/157436571815778829
creation_time: 1762697563277
experiment_id: '157436571815778829'
last_update_time: 1762697563277
lifecycle_stage: active
name: dynamic_topoqa
