artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691/0ddcea7c91ce4605bc15fee19cefef2a/artifacts
end_time: 1764703512207
entry_point_name: ''
experiment_id: '704094476654428691'
lifecycle_stage: active
run_id: 0ddcea7c91ce4605bc15fee19cefef2a
run_name: sched_boost_lr035_lean_seed222_2025-12-02_19-03-07
source_name: ''
source_type: 4
source_version: ''
start_time: 1764702192692
status: 3
tags: []
user_id: vscode
