artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/572946763623760538/36e94a7c10cb45a5a2aa0b02f52a0970/artifacts
end_time: 1764840353847
entry_point_name: ''
experiment_id: '572946763623760538'
lifecycle_stage: active
run_id: 36e94a7c10cb45a5a2aa0b02f52a0970
run_name: polish_lr_low_seed101_2025-12-04_09-14-33
source_name: ''
source_type: 4
source_version: ''
start_time: 1764839686676
status: 3
tags: []
user_id: vscode
