artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522/783ff4a43c4c4395a2db0e1a9d2f9024/artifacts
end_time: 1763094586719
entry_point_name: ''
experiment_id: '195331767355654522'
lifecycle_stage: active
run_id: 783ff4a43c4c4395a2db0e1a9d2f9024
run_name: large_batch_sched_boost_seed222_2025-11-14_03-54-38
source_name: ''
source_type: 4
source_version: ''
start_time: 1763092502625
status: 3
tags: []
user_id: kn
