artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/9ef0bdcde4164793b384dff769e7a3cf/artifacts
end_time: 1764077291329
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 9ef0bdcde4164793b384dff769e7a3cf
run_name: sched_boost_seed222_2025-11-25_09-32-00_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764076610492
status: 3
tags: []
user_id: vscode
