artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/9e565a6cd6e54122a5a43de19e5b2a52/artifacts
end_time: 1762276092659
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: 9e565a6cd6e54122a5a43de19e5b2a52
run_name: seed222_tiny_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762273518084
status: 3
tags: []
user_id: kn
