artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/c5932dc7cb8e46b3aaad2e5b7d6013f7/artifacts
end_time: 1763063506948
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: c5932dc7cb8e46b3aaad2e5b7d6013f7
run_name: sched_boost_lr035_seed222_2025-11-13_10-10-08_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1763062090241
status: 3
tags: []
user_id: kn
