artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/8e3232ab2dcd47ecbd063536812771fa/artifacts
end_time: 1766116522043
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: 8e3232ab2dcd47ecbd063536812771fa
run_name: polish_lr_low_seed101_2025-12-18_20-18-25_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1766115251495
status: 3
tags: []
user_id: vscode
