artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/3168df35a16348e7a98fefff1e937117/artifacts
end_time: 1762105748561
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 3168df35a16348e7a98fefff1e937117
run_name: large_batch_sched_boost_seed222_2025-11-02_16-52-32
source_name: ''
source_type: 4
source_version: ''
start_time: 1762102366335
status: 3
tags: []
user_id: kn
