artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/c0e5bda9a82844fca5717a6a652be8b7/artifacts
end_time: 1762309180456
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: c0e5bda9a82844fca5717a6a652be8b7
run_name: sched_boost_seed222_2025-11-04_19-48-43_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1762307330350
status: 3
tags: []
user_id: kn
