artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/6ae01f380efe466d832d45d5edcb1910/artifacts
end_time: 1764305723263
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 6ae01f380efe466d832d45d5edcb1910
run_name: sched_boost_lr035_seed222_2025-11-27_23-38-29_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1764304090270
status: 3
tags: []
user_id: vscode
