artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/7b2f107d15c1497186e827ecfad23de2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: 7b2f107d15c1497186e827ecfad23de2
run_name: polish_seed888_2025-11-30_11-41-37
source_name: ''
source_type: 4
source_version: ''
start_time: 1764502908987
status: 1
tags: []
user_id: vscode
