artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/666ea42ab5474a31a0c783acdea6f530/artifacts
end_time: 1765531818888
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: 666ea42ab5474a31a0c783acdea6f530
run_name: sched_boost_lean_seed222_2025-12-12_08-43-08_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1765531805660
status: 3
tags: []
user_id: vscode
