# Default configuration for qtdaqa/new_graph_builder
# Copy this file next to your work-dir and edit as needed.

interface:
  cutoff: 14.0        # Å distance for interface extraction (should cover the largest edge band)
  coordinate_decimals: 3

topology:
  neighbor_distance: 8.0
  filtration_cutoff: 8.0
  min_persistence: 0.01
  dedup_sort: false

node_drop_na: false

edge:
  bands:
    - {label: short,  min_distance: 0.0,  max_distance: 6.0}
    - {label: medium, min_distance: 6.0,  max_distance: 10.0}
    - {label: long,   min_distance: 10.0, max_distance: 14.0}
  histogram_bins: [0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0]
  contact_threshold: 5.0
  include_inverse_distance: true
  include_unit_vector: true
  unit_vector_epsilon: 1.0e-8
  normalize: none      # supported: none
