artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/e7dfeb0201d4410494be83a20d8ebafa/artifacts
end_time: 1762113900909
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: e7dfeb0201d4410494be83a20d8ebafa
run_name: sched_boost_seed222_2025-11-02_10-38-47_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1762112974164
status: 3
tags: []
user_id: kn
