artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/ebeff4a9e2924cb3a48d6dd90f65b275/artifacts
end_time: 1766102511137
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: ebeff4a9e2924cb3a48d6dd90f65b275
run_name: polish_lr_low_seed101_2025-12-18_20-18-25
source_name: ''
source_type: 4
source_version: ''
start_time: 1766089112260
status: 3
tags: []
user_id: vscode
