artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/757735313826032059/c21c4f9c08db4cb5b110f14e57d48c45/artifacts
end_time: 1763803882272
entry_point_name: ''
experiment_id: '757735313826032059'
lifecycle_stage: active
run_id: c21c4f9c08db4cb5b110f14e57d48c45
run_name: sched_boost_seed777_2025-11-22_09-04-13
source_name: ''
source_type: 4
source_version: ''
start_time: 1763802272983
status: 3
tags: []
user_id: vscode
