artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/960847033820624533/bdecb4dad38c476b912ec5b4c3dea55d/artifacts
end_time: 1762842689336
entry_point_name: ''
experiment_id: '960847033820624533'
lifecycle_stage: active
run_id: bdecb4dad38c476b912ec5b4c3dea55d
run_name: sched_boost_seed1337_2025-11-11_05-16-44
source_name: ''
source_type: 4
source_version: ''
start_time: 1762838231843
status: 3
tags: []
user_id: kn
