artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/b26dd555172642d9a6819177bb3821a1/artifacts
end_time: 1764014011290
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: b26dd555172642d9a6819177bb3821a1
run_name: latest_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1764013378816
status: 3
tags: []
user_id: vscode
