artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/167eb7d03c5c41daa9b36234ea38f689/artifacts
end_time: 1765115799515
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: 167eb7d03c5c41daa9b36234ea38f689
run_name: polish_lr_low_seed101_2025-12-07_12-53-40
source_name: ''
source_type: 4
source_version: ''
start_time: 1765112026643
status: 3
tags: []
user_id: vscode
