artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/87209c88cb4e452f9d700c7b4fba6f76/artifacts
end_time: 1765031060846
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: 87209c88cb4e452f9d700c7b4fba6f76
run_name: sched_boost_lean_seed222_2025-12-06_12-42-55_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765030337416
status: 3
tags: []
user_id: vscode
