accelerator: cpu
accumulate_grad_batches: 16
attention_head: 8
batch_size: 16
devices: 1
early_stopping_patience: 25
graph_dir: ../../new_graph_builder/output/24d_edges_adjusted_dataset/graph_data
learning_rate: 0.005
lr_scheduler_factor: 0.4
lr_scheduler_patience: 12
num_epochs: 200
num_workers: 0
pooling_type: mean
precision: 32
save_dir: ./training_runs
seed: 222
train_label_file: ./train.csv
val_label_file: ./val.csv
