artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/53a47615b20a4e7980d9a1775fa81e24/artifacts
end_time: 1764017457676
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: 53a47615b20a4e7980d9a1775fa81e24
run_name: latest_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764015906971
status: 3
tags: []
user_id: vscode
