artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522/d5b72d49fafe44b4b6ed886bc300b9b4/artifacts
end_time: 1763087281473
entry_point_name: ''
experiment_id: '195331767355654522'
lifecycle_stage: active
run_id: d5b72d49fafe44b4b6ed886bc300b9b4
run_name: sched_boost_lr035_seed222_2025-11-14_00-52-06
source_name: ''
source_type: 4
source_version: ''
start_time: 1763081550985
status: 3
tags: []
user_id: kn
