artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/983626403599653281/3e28d697ea1d491cbc42fd974592bfa2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '983626403599653281'
lifecycle_stage: active
run_id: 3e28d697ea1d491cbc42fd974592bfa2
run_name: sched_boost_seed222_2025-11-05_23-27-09
source_name: ''
source_type: 4
source_version: ''
start_time: 1762385242611
status: 1
tags: []
user_id: kn
