artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932/2d3fbc0df71044ab992e65463f2f1fb1/artifacts
end_time: 1764650771249
entry_point_name: ''
experiment_id: '553929320275185932'
lifecycle_stage: active
run_id: 2d3fbc0df71044ab992e65463f2f1fb1
run_name: polish_seed101_2025-12-01_17-16-30_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764649763327
status: 3
tags: []
user_id: vscode
