artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188
creation_time: 1762545934632
experiment_id: '818209245385519188'
last_update_time: 1762545934632
lifecycle_stage: active
name: dynamic_topoqa
