artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/d4bf2e272c354159b349b70dbff1c990/artifacts
end_time: 1765549053013
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: d4bf2e272c354159b349b70dbff1c990
run_name: polish_lr_low_seed555_2025-12-12_11-38-01_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1765548954345
status: 3
tags: []
user_id: vscode
