artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478/fbd728a08f0845f3bef4e46675123eeb/artifacts
end_time: 1765892101300
entry_point_name: ''
experiment_id: '994680267604837478'
lifecycle_stage: active
run_id: fbd728a08f0845f3bef4e46675123eeb
run_name: polish_seed101_2025-12-16_12-26-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1765888015059
status: 3
tags: []
user_id: vscode
