artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/d00fff1ad9994f178405b9927fbeeff2/artifacts
end_time: 1766082777976
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: d00fff1ad9994f178405b9927fbeeff2
run_name: sched_boost_lean_seed222_2025-12-18_18-16-30
source_name: ''
source_type: 4
source_version: ''
start_time: 1766081797713
status: 3
tags: []
user_id: vscode
