artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/536467477892488150/07c78966b64a4b12869c77d340d5e930/artifacts
end_time: null
entry_point_name: ''
experiment_id: '536467477892488150'
lifecycle_stage: active
run_id: 07c78966b64a4b12869c77d340d5e930
run_name: large_batch_sched_boost_seed222_2025-11-14_21-35-06
source_name: ''
source_type: 4
source_version: ''
start_time: 1763156135101
status: 1
tags: []
user_id: kn
