artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/4082bda806ed417eacc53f40cb4b5fce/artifacts
end_time: 1763028608376
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: 4082bda806ed417eacc53f40cb4b5fce
run_name: sched_boost_seed1337_2025-11-13_08-49-51
source_name: ''
source_type: 4
source_version: ''
start_time: 1763023808505
status: 3
tags: []
user_id: kn
