artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/203034696812255868/8a56308e67b64c1da31f4b64a1d884e3/artifacts
end_time: 1762613089981
entry_point_name: ''
experiment_id: '203034696812255868'
lifecycle_stage: active
run_id: 8a56308e67b64c1da31f4b64a1d884e3
run_name: large_batch_sched_boost_seed222_2025-11-08_14-20-10
source_name: ''
source_type: 4
source_version: ''
start_time: 1762611632483
status: 3
tags: []
user_id: kn
