artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/80e92caba0d04e5d957c37d4eb22df03/artifacts
end_time: 1765109836780
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: 80e92caba0d04e5d957c37d4eb22df03
run_name: sched_boost_lean_seed222_2025-12-07_11-30-22_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765109545487
status: 3
tags: []
user_id: vscode
