artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/fbb49b3d042c45bcbe2d189e3f3d8a84/artifacts
end_time: 1765109896398
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: fbb49b3d042c45bcbe2d189e3f3d8a84
run_name: sched_boost_lean_seed222_2025-12-07_11-30-22_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1765109882590
status: 3
tags: []
user_id: vscode
