artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/263834183455537235/ff659774655b4b7cba3f1a24cef5231d/artifacts
end_time: 1763848072827
entry_point_name: ''
experiment_id: '263834183455537235'
lifecycle_stage: active
run_id: ff659774655b4b7cba3f1a24cef5231d
run_name: sched_boost_seed777_2025-11-22_21-28-09
source_name: ''
source_type: 4
source_version: ''
start_time: 1763846918596
status: 3
tags: []
user_id: vscode
