artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/fee8c05b12934f3eba38c9cd64d4e899/artifacts
end_time: null
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: fee8c05b12934f3eba38c9cd64d4e899
run_name: sched_boost_seed222_fastdev_2025-11-04_14-47-47
source_name: ''
source_type: 4
source_version: ''
start_time: 1762267683624
status: 1
tags: []
user_id: kn
