artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746
creation_time: 1763978519155
experiment_id: '284713950887304746'
last_update_time: 1763978519155
lifecycle_stage: active
name: dynamic_topoqa
