artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/97429e37da8b4f778ad662adbe2815c6/artifacts
end_time: 1765285592300
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: 97429e37da8b4f778ad662adbe2815c6
run_name: polish_lr_low_seed888_2025-12-09_11-32-35
source_name: ''
source_type: 4
source_version: ''
start_time: 1765279959989
status: 3
tags: []
user_id: vscode
