artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974/d4ab0605cfac4d7db4d32622e41b8dc5/artifacts
end_time: 1762690656104
entry_point_name: ''
experiment_id: '278908513362295974'
lifecycle_stage: active
run_id: d4ab0605cfac4d7db4d32622e41b8dc5
run_name: sched_boost_seed777_2025-11-09_08-46-53_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762690188423
status: 3
tags: []
user_id: kn
