artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/af8ebba5356c488785db8dc43aa3415b/artifacts
end_time: 1765279954649
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: af8ebba5356c488785db8dc43aa3415b
run_name: polish_seed888_2025-12-09_10-46-11
source_name: ''
source_type: 4
source_version: ''
start_time: 1765277175899
status: 3
tags: []
user_id: vscode
