artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/830446690413640518/ba7a380dca974e918efa629d54f9e260/artifacts
end_time: 1763292306510
entry_point_name: ''
experiment_id: '830446690413640518'
lifecycle_stage: active
run_id: ba7a380dca974e918efa629d54f9e260
run_name: large_batch_sched_boost_seed222_2025-11-16_10-52-05
source_name: ''
source_type: 4
source_version: ''
start_time: 1763290356106
status: 3
tags: []
user_id: kn
