artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/fec6d8e48f164afabf239294540e2c68/artifacts
end_time: 1763995532650
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: fec6d8e48f164afabf239294540e2c68
run_name: sched_boost_lr035_seed777_2025-11-24_11-56-59_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1763994925802
status: 3
tags: []
user_id: vscode
