artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/9cfcbb5005cc432e877ef27619cf599a/artifacts
end_time: 1764463321389
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: 9cfcbb5005cc432e877ef27619cf599a
run_name: sched_boost_lr035_lean_seed222_2025-11-29_23-48-40
source_name: ''
source_type: 4
source_version: ''
start_time: 1764460131338
status: 3
tags: []
user_id: vscode
