artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/203034696812255868/3f4e8a18bba14b38a00ee2cd0d708b8c/artifacts
end_time: 1762600058348
entry_point_name: ''
experiment_id: '203034696812255868'
lifecycle_stage: active
run_id: 3f4e8a18bba14b38a00ee2cd0d708b8c
run_name: sched_boost_lr035_seed222_2025-11-08_10-43-48
source_name: ''
source_type: 4
source_version: ''
start_time: 1762598645874
status: 3
tags: []
user_id: kn
