artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/28bbe25c6747438ab8a1e104fc871587/artifacts
end_time: 1764365943316
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 28bbe25c6747438ab8a1e104fc871587
run_name: latest_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764364151919
status: 3
tags: []
user_id: vscode
