artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974/7c76814f65a24ecba1adac60bcbc3345/artifacts
end_time: 1762678012741
entry_point_name: ''
experiment_id: '278908513362295974'
lifecycle_stage: active
run_id: 7c76814f65a24ecba1adac60bcbc3345
run_name: sched_boost_seed222_2025-11-09_08-27-06
source_name: ''
source_type: 4
source_version: ''
start_time: 1762676848025
status: 3
tags: []
user_id: kn
