artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/bb0e2b5bc9144d7e91e0c0bbe8c2bcc8/artifacts
end_time: 1762102351586
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: bb0e2b5bc9144d7e91e0c0bbe8c2bcc8
run_name: sched_boost_lr035_seed1337_2025-11-02_15-34-09
source_name: ''
source_type: 4
source_version: ''
start_time: 1762097663536
status: 3
tags: []
user_id: kn
