artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/602587911472957613/9acea1a82d88452bbd2cfc9ff01930fa/artifacts
end_time: 1762086917910
entry_point_name: ''
experiment_id: '602587911472957613'
lifecycle_stage: active
run_id: 9acea1a82d88452bbd2cfc9ff01930fa
run_name: sched_boost_seed777_2025-11-02_12-02-03
source_name: ''
source_type: 4
source_version: ''
start_time: 1762084937453
status: 3
tags: []
user_id: kn
