artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/de25fdf832434fdda9581ee36788a3ea/artifacts
end_time: 1763922759976
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: de25fdf832434fdda9581ee36788a3ea
run_name: large_batch_sched_boost_seed1337_2025-11-23_18-03-05
source_name: ''
source_type: 4
source_version: ''
start_time: 1763921023779
status: 3
tags: []
user_id: vscode
