artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/2e9f75cffa514e8dbc94ca5687a531b0/artifacts
end_time: 1766118044456
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: 2e9f75cffa514e8dbc94ca5687a531b0
run_name: polish_lr_low_seed101_2025-12-18_20-18-25_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1766117278145
status: 3
tags: []
user_id: vscode
