artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/994680267604837478/4ec36acd120e4df69d9c28f0d92eba8b/artifacts
end_time: 1765886576749
entry_point_name: ''
experiment_id: '994680267604837478'
lifecycle_stage: active
run_id: 4ec36acd120e4df69d9c28f0d92eba8b
run_name: sched_boost_lr035_lean_seed222_2025-12-16_11-44-37
source_name: ''
source_type: 4
source_version: ''
start_time: 1765885481790
status: 3
tags: []
user_id: vscode
