artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/263834183455537235/71651dbf65664bc7b6e83ed5eef6294b/artifacts
end_time: 1763846889165
entry_point_name: ''
experiment_id: '263834183455537235'
lifecycle_stage: active
run_id: 71651dbf65664bc7b6e83ed5eef6294b
run_name: sched_boost_seed222_2025-11-22_21-10-48
source_name: ''
source_type: 4
source_version: ''
start_time: 1763845878378
status: 3
tags: []
user_id: vscode
