artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/b7b4df7f91a54e58a00ad7b76ccf0ded/artifacts
end_time: 1762553861369
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: b7b4df7f91a54e58a00ad7b76ccf0ded
run_name: large_batch_sched_boost_seed222_2025-11-07_21-00-06_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1762553227907
status: 3
tags: []
user_id: kn
