artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/8f91d1abec2d418b92e6a9cedf838a02/artifacts
end_time: 1765085024898
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: 8f91d1abec2d418b92e6a9cedf838a02
run_name: polish_seed101_2025-12-06_15-03-20_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765083704375
status: 3
tags: []
user_id: vscode
