artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974/e132226373da4dc49b8f51ddda7dd7ee/artifacts
end_time: 1762682834244
entry_point_name: ''
experiment_id: '278908513362295974'
lifecycle_stage: active
run_id: e132226373da4dc49b8f51ddda7dd7ee
run_name: sched_boost_lr035_seed777_2025-11-09_09-51-33
source_name: ''
source_type: 4
source_version: ''
start_time: 1762681912659
status: 3
tags: []
user_id: kn
