artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/cf57afbf4cca43b8a87c95a3b2100a23/artifacts
end_time: null
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: cf57afbf4cca43b8a87c95a3b2100a23
run_name: sched_boost_seed777_2025-11-27_21-43-05
source_name: ''
source_type: 4
source_version: ''
start_time: 1764279797050
status: 1
tags: []
user_id: vscode
