artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932/99ed44bfa0a94723be7c57c446b4d964/artifacts
end_time: 1764604351060
entry_point_name: ''
experiment_id: '553929320275185932'
lifecycle_stage: active
run_id: 99ed44bfa0a94723be7c57c446b4d964
run_name: sched_boost_lean_seed222_2025-12-01_15-11-21
source_name: ''
source_type: 4
source_version: ''
start_time: 1764601890582
status: 3
tags: []
user_id: vscode
