artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/b641e2c5ac884d77abf17becfabc5a23/artifacts
end_time: 1765109537598
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: b641e2c5ac884d77abf17becfabc5a23
run_name: large_batch_sched_boost_lean_seed222_2025-12-07_11-59-11
source_name: ''
source_type: 4
source_version: ''
start_time: 1765108757506
status: 3
tags: []
user_id: vscode
