artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/830446690413640518/0e3e72ba7a924988aaed21fd2abdbb54/artifacts
end_time: 1763288780822
entry_point_name: ''
experiment_id: '830446690413640518'
lifecycle_stage: active
run_id: 0e3e72ba7a924988aaed21fd2abdbb54
run_name: sched_boost_lr035_seed777_2025-11-16_09-58-59
source_name: ''
source_type: 4
source_version: ''
start_time: 1763287174090
status: 3
tags: []
user_id: kn
