artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/808112237968465609/28bced96de7442dbbbefec770a3d615a/artifacts
end_time: 1765125327780
entry_point_name: ''
experiment_id: '808112237968465609'
lifecycle_stage: active
run_id: 28bced96de7442dbbbefec770a3d615a
run_name: polish_lr_low_seed555_2025-12-07_14-16-17_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1765125243950
status: 3
tags: []
user_id: vscode
