artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592
creation_time: 1762267151269
experiment_id: '467730969356788592'
last_update_time: 1762267151269
lifecycle_stage: active
name: dynamic_topoqa
