artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/133858506419254271/afa305506cd247cda66da397f39bb0d1/artifacts
end_time: 1764993267717
entry_point_name: ''
experiment_id: '133858506419254271'
lifecycle_stage: active
run_id: afa305506cd247cda66da397f39bb0d1
run_name: polish_lr_low_seed555_2025-12-06_02-59-48
source_name: ''
source_type: 4
source_version: ''
start_time: 1764989993289
status: 3
tags: []
user_id: vscode
