artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/f004e1d9a4a54ab9b15c9cac50bac02e/artifacts
end_time: 1765494822043
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: f004e1d9a4a54ab9b15c9cac50bac02e
run_name: polish_seed888_2025-12-11_21-29-03_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1765494514556
status: 3
tags: []
user_id: vscode
