artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932/e34ba9dd169042ba94ae96417b5cc9bc/artifacts
end_time: 1764639781964
entry_point_name: ''
experiment_id: '553929320275185932'
lifecycle_stage: active
run_id: e34ba9dd169042ba94ae96417b5cc9bc
run_name: polish_seed888_2025-12-01_23-54-02
source_name: ''
source_type: 4
source_version: ''
start_time: 1764633251123
status: 3
tags: []
user_id: vscode
