artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051/748bbc0eed0e4998814ebb3b9a078bf7/artifacts
end_time: 1763037905527
entry_point_name: ''
experiment_id: '173754659977499051'
lifecycle_stage: active
run_id: 748bbc0eed0e4998814ebb3b9a078bf7
run_name: sched_boost_lr035_seed777_2025-11-13_11-35-49
source_name: ''
source_type: 4
source_version: ''
start_time: 1763033767620
status: 3
tags: []
user_id: kn
