artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691/d922feb68d8d4a8b9cbbb745cdfde817/artifacts
end_time: 1764717674219
entry_point_name: ''
experiment_id: '704094476654428691'
lifecycle_stage: active
run_id: d922feb68d8d4a8b9cbbb745cdfde817
run_name: polish_seed888_2025-12-02_22-48-39
source_name: ''
source_type: 4
source_version: ''
start_time: 1764715725214
status: 3
tags: []
user_id: vscode
