artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/5f1d27faad6243ffa0ee56e4d980230e/artifacts
end_time: 1763996132970
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: 5f1d27faad6243ffa0ee56e4d980230e
run_name: sched_boost_lr035_seed777_2025-11-24_11-56-59_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1763995573569
status: 3
tags: []
user_id: vscode
