artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/7936eb760a3c481c9b852baad1cd485b/artifacts
end_time: 1764465204795
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: 7936eb760a3c481c9b852baad1cd485b
run_name: sched_boost_lr035_lean_seed222_2025-11-29_23-48-40_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1764464306607
status: 3
tags: []
user_id: vscode
