artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/5f14a80df95948b6931e1f7c25763048/artifacts
end_time: 1764520528405
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: 5f14a80df95948b6931e1f7c25763048
run_name: latest_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764518803360
status: 3
tags: []
user_id: vscode
