artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/368408924535291840
creation_time: 1763106105941
experiment_id: '368408924535291840'
last_update_time: 1763106105941
lifecycle_stage: active
name: dynamic_topoqa
