artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223/d9e2422be1404cb88bd37bc2690a9aa5/artifacts
end_time: 1765922980067
entry_point_name: ''
experiment_id: '578842538229463223'
lifecycle_stage: active
run_id: d9e2422be1404cb88bd37bc2690a9aa5
run_name: large_batch_sched_boost_lean_seed222_2025-12-16_21-51-52_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765922723747
status: 3
tags: []
user_id: vscode
