artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/6d537c9f68524eaaafff9d31f58727ee/artifacts
end_time: 1764367752759
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 6d537c9f68524eaaafff9d31f58727ee
run_name: latest_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1764365955997
status: 3
tags: []
user_id: vscode
