artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/263834183455537235/3c17897c48ea4d6db3a297d5bbb50ea4/artifacts
end_time: 1763858243330
entry_point_name: ''
experiment_id: '263834183455537235'
lifecycle_stage: active
run_id: 3c17897c48ea4d6db3a297d5bbb50ea4
run_name: large_batch_sched_boost_seed1337_2025-11-23_00-10-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1763856676947
status: 3
tags: []
user_id: vscode
