artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/384024837216329171/94ed8e93cb7d452986bd6c893b3da4ec/artifacts
end_time: 1766085871392
entry_point_name: ''
experiment_id: '384024837216329171'
lifecycle_stage: active
run_id: 94ed8e93cb7d452986bd6c893b3da4ec
run_name: sched_boost_lr035_lean_seed222_2025-12-18_18-32-58_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1766085456431
status: 3
tags: []
user_id: vscode
