artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/1ed1dc7238084c968346622a642efa33/artifacts
end_time: 1763956335169
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: 1ed1dc7238084c968346622a642efa33
run_name: latest_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1763955457093
status: 3
tags: []
user_id: vscode
