artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/173754659977499051
creation_time: 1763016223442
experiment_id: '173754659977499051'
last_update_time: 1763016223442
lifecycle_stage: active
name: dynamic_topoqa
