artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691/1ba3793dd27a42da902105ae9a83cab8/artifacts
end_time: 1764709183825
entry_point_name: ''
experiment_id: '704094476654428691'
lifecycle_stage: active
run_id: 1ba3793dd27a42da902105ae9a83cab8
run_name: polish_lr_low_seed101_2025-12-02_20-09-37
source_name: ''
source_type: 4
source_version: ''
start_time: 1764706182720
status: 3
tags: []
user_id: vscode
