artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/dce521625ca3420dac34a02c588e2df8/artifacts
end_time: 1765495428898
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: dce521625ca3420dac34a02c588e2df8
run_name: polish_seed888_2025-12-11_21-29-03_phase2_seed888
source_name: ''
source_type: 4
source_version: ''
start_time: 1765495138812
status: 3
tags: []
user_id: vscode
