artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/abee06af59ca4513abb621fac3f4e0c7/artifacts
end_time: 1765266839190
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: abee06af59ca4513abb621fac3f4e0c7
run_name: sched_boost_lean_seed222_2025-12-09_06-58-32_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1765266501051
status: 3
tags: []
user_id: vscode
