artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/56c43d99e69c4806b93d65e93ee5f1ba/artifacts
end_time: null
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: 56c43d99e69c4806b93d65e93ee5f1ba
run_name: polish_lr_low_seed555_2025-12-06_20-33-54
source_name: ''
source_type: 4
source_version: ''
start_time: 1765053240590
status: 1
tags: []
user_id: vscode
