artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/960847033820624533/4a56e1519ac24a9fb61c03ed7dba94b7/artifacts
end_time: 1762856735993
entry_point_name: ''
experiment_id: '960847033820624533'
lifecycle_stage: active
run_id: 4a56e1519ac24a9fb61c03ed7dba94b7
run_name: sched_boost_lr035_seed1337_2025-11-11_09-02-41
source_name: ''
source_type: 4
source_version: ''
start_time: 1762851785064
status: 3
tags: []
user_id: kn
