artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/278908513362295974/32cfa6f2ca7240d996192cc39b9863fa/artifacts
end_time: 1762684549052
entry_point_name: ''
experiment_id: '278908513362295974'
lifecycle_stage: active
run_id: 32cfa6f2ca7240d996192cc39b9863fa
run_name: large_batch_sched_boost_seed222_2025-11-09_10-23-27
source_name: ''
source_type: 4
source_version: ''
start_time: 1762683825994
status: 3
tags: []
user_id: kn
