artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/203034696812255868/cbbf9c33afd34b078d0ca64fdf48b355/artifacts
end_time: null
entry_point_name: ''
experiment_id: '203034696812255868'
lifecycle_stage: active
run_id: cbbf9c33afd34b078d0ca64fdf48b355
run_name: polish_template_smoke
source_name: ''
source_type: 4
source_version: ''
start_time: 1762619620277
status: 1
tags: []
user_id: kn
