artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/686301252057198949/d1b1b93cceb64eca9225b050a80a2a5b/artifacts
end_time: 1765482371519
entry_point_name: ''
experiment_id: '686301252057198949'
lifecycle_stage: active
run_id: d1b1b93cceb64eca9225b050a80a2a5b
run_name: polish_lr_low_seed101_2025-12-11_18-45-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1765478755512
status: 3
tags: []
user_id: vscode
