artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/5d7a15f632d54ee493ff31d7230beace/artifacts
end_time: 1766144432050
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: 5d7a15f632d54ee493ff31d7230beace
run_name: sched_boost_lr035_lean_seed222_2025-12-19_11-22-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1766143380375
status: 3
tags: []
user_id: vscode
