artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/2cd8593747764fd7b8ea6e31b60cb24b/artifacts
end_time: 1765266495649
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: 2cd8593747764fd7b8ea6e31b60cb24b
run_name: sched_boost_lean_seed222_2025-12-09_06-58-32_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1765266081914
status: 3
tags: []
user_id: vscode
