artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/195331767355654522/33ecffb6369d4ae796a40aab1f474de2/artifacts
end_time: 1763092478077
entry_point_name: ''
experiment_id: '195331767355654522'
lifecycle_stage: active
run_id: 33ecffb6369d4ae796a40aab1f474de2
run_name: sched_boost_lr035_seed1337_2025-11-14_03-12-04
source_name: ''
source_type: 4
source_version: ''
start_time: 1763089947818
status: 3
tags: []
user_id: kn
