artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223/f5bbb5d824014b3b8fa6c6f0baa85544/artifacts
end_time: 1765928905087
entry_point_name: ''
experiment_id: '578842538229463223'
lifecycle_stage: active
run_id: f5bbb5d824014b3b8fa6c6f0baa85544
run_name: polish_seed555_2025-12-16_23-18-21
source_name: ''
source_type: 4
source_version: ''
start_time: 1765927108415
status: 3
tags: []
user_id: vscode
