artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/960847033820624533/a72beb86e64e4fcb9ab28f96da0f6428/artifacts
end_time: 1762893784580
entry_point_name: ''
experiment_id: '960847033820624533'
lifecycle_stage: active
run_id: a72beb86e64e4fcb9ab28f96da0f6428
run_name: sched_boost_lr035_seed1337_2025-11-11_09-02-41_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1762891798781
status: 3
tags: []
user_id: kn
