name: topoqa-gpu
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy=1.10.0
  - scikit-learn=1.2.2
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8.5.0_0
  - torchvision=0.14.1=py310_cu117
  - torchaudio=0.13.1=py310_cu117
  - pytorch-cuda=11.7
  - pytorch-lightning=1.9.5
  - torchmetrics=0.11.4
  - pyg=2.2.0
  - pytorch-cluster=1.6.0
  - pytorch-scatter=2.1.0
  - pytorch-sparse=0.6.16
  - pytorch-spline-conv=1.2.1
  - cudatoolkit=11.7
  - biopython=1.80
  - gudhi=3.6.0
  - joblib=1.2.0
  - networkx=2.8.8
  - h5py=3.8.0
  - tqdm=4.65.0
  - pip=23.2.1
  - pip:
      - wandb==0.15.8
      - PyYAML==6.0
