artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/ed7815bc10b7481c9fd6b25f9b260f38/artifacts
end_time: 1763957044691
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: ed7815bc10b7481c9fd6b25f9b260f38
run_name: latest_phase2_seed101
source_name: ''
source_type: 4
source_version: ''
start_time: 1763956376664
status: 3
tags: []
user_id: vscode
