artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/581198018460776165/174d14826eca4dfebcddafd4534a0fae/artifacts
end_time: 1766166349874
entry_point_name: ''
experiment_id: '581198018460776165'
lifecycle_stage: active
run_id: 174d14826eca4dfebcddafd4534a0fae
run_name: polish_seed555_2025-12-19_17-06-58
source_name: ''
source_type: 4
source_version: ''
start_time: 1766164028866
status: 3
tags: []
user_id: vscode
