artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/843924752530628821/d131645ccdf84990b55d4a6a3b95e3b7/artifacts
end_time: 1765531500302
entry_point_name: ''
experiment_id: '843924752530628821'
lifecycle_stage: active
run_id: d131645ccdf84990b55d4a6a3b95e3b7
run_name: large_batch_sched_boost_lean_seed222_2025-12-12_09-11-54
source_name: ''
source_type: 4
source_version: ''
start_time: 1765530719735
status: 3
tags: []
user_id: vscode
