artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/688850596195161062/c423af947fe54c6c8c3b6f8eab6e2a7c/artifacts
end_time: 1764464294759
entry_point_name: ''
experiment_id: '688850596195161062'
lifecycle_stage: active
run_id: c423af947fe54c6c8c3b6f8eab6e2a7c
run_name: large_batch_sched_boost_lean_seed222_2025-11-30_00-42-01
source_name: ''
source_type: 4
source_version: ''
start_time: 1764463333157
status: 3
tags: []
user_id: vscode
