artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/450284739565994813/2a25277c7fcd48e1b6d8f83bb91d144f/artifacts
end_time: 1764341818093
entry_point_name: ''
experiment_id: '450284739565994813'
lifecycle_stage: active
run_id: 2a25277c7fcd48e1b6d8f83bb91d144f
run_name: polish_seed555_2025-11-28_11-56-25
source_name: ''
source_type: 4
source_version: ''
start_time: 1764330997603
status: 3
tags: []
user_id: vscode
