artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/818209245385519188/ddbfa861907f440db229a92d34a53a5f/artifacts
end_time: 1762580563444
entry_point_name: ''
experiment_id: '818209245385519188'
lifecycle_stage: active
run_id: ddbfa861907f440db229a92d34a53a5f
run_name: large_batch_sched_boost_seed1337_2025-11-08_05-11-04
source_name: ''
source_type: 4
source_version: ''
start_time: 1762578680572
status: 3
tags: []
user_id: kn
