artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/553929320275185932
creation_time: 1764601890543
experiment_id: '553929320275185932'
last_update_time: 1764601890543
lifecycle_stage: active
name: dynamic_topoqa
