artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/578842538229463223
creation_time: 1765919091703
experiment_id: '578842538229463223'
last_update_time: 1765919091703
lifecycle_stage: active
name: dynamic_topoqa
