artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/5f98bece542145a09b3da5dcdcf6341e/artifacts
end_time: 1765267159376
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: 5f98bece542145a09b3da5dcdcf6341e
run_name: sched_boost_lean_seed222_2025-12-09_06-58-32_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1765266844579
status: 3
tags: []
user_id: vscode
