artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/467730969356788592/b5fcc088cf0142c699aceda20ad4c9e4/artifacts
end_time: 1762369840523
entry_point_name: ''
experiment_id: '467730969356788592'
lifecycle_stage: active
run_id: b5fcc088cf0142c699aceda20ad4c9e4
run_name: sched_boost_seed222_2025-11-05_07-45-31_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1762366869399
status: 3
tags: []
user_id: kn
