artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304/e8edfd625a2743e4b75a80a338a118ac/artifacts
end_time: 1765083697173
entry_point_name: ''
experiment_id: '403474673705615304'
lifecycle_stage: active
run_id: e8edfd625a2743e4b75a80a338a118ac
run_name: polish_lr_low_seed888_2025-12-07_03-27-12
source_name: ''
source_type: 4
source_version: ''
start_time: 1765078038989
status: 3
tags: []
user_id: vscode
