artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/368408924535291840/4fe5da31c2d9452fa44d04fe18592f98/artifacts
end_time: 1763128926540
entry_point_name: ''
experiment_id: '368408924535291840'
lifecycle_stage: active
run_id: 4fe5da31c2d9452fa44d04fe18592f98
run_name: large_batch_sched_boost_seed1337_2025-11-14_13-24-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1763126713721
status: 3
tags: []
user_id: kn
