artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222
creation_time: 1763908571343
experiment_id: '651677857607399222'
last_update_time: 1763908571343
lifecycle_stage: active
name: dynamic_topoqa
