artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/368408924535291840/bbc80d014b6f4ecba9425ba9b0238f69/artifacts
end_time: 1763114530895
entry_point_name: ''
experiment_id: '368408924535291840'
lifecycle_stage: active
run_id: bbc80d014b6f4ecba9425ba9b0238f69
run_name: sched_boost_seed1337_2025-11-14_09-06-54
source_name: ''
source_type: 4
source_version: ''
start_time: 1763111239889
status: 3
tags: []
user_id: kn
