artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/830446690413640518
creation_time: 1763279502741
experiment_id: '830446690413640518'
last_update_time: 1763279502741
lifecycle_stage: active
name: dynamic_topoqa
