artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691/2ed425ce5cfa46a1b03b1dc606c40588/artifacts
end_time: 1764704622650
entry_point_name: ''
experiment_id: '704094476654428691'
lifecycle_stage: active
run_id: 2ed425ce5cfa46a1b03b1dc606c40588
run_name: large_batch_sched_boost_lean_seed222_2025-12-02_19-25-12_phase2_seed555
source_name: ''
source_type: 4
source_version: ''
start_time: 1764704608901
status: 3
tags: []
user_id: vscode
