artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/d511bd060564420e988eceadf6c135a5/artifacts
end_time: 1763935688839
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: d511bd060564420e988eceadf6c135a5
run_name: polish_lr_low_seed101_2025-11-23_21-10-39
source_name: ''
source_type: 4
source_version: ''
start_time: 1763932277357
status: 3
tags: []
user_id: vscode
