artifact_location: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/403474673705615304
creation_time: 1765024983938
experiment_id: '403474673705615304'
last_update_time: 1765024983938
lifecycle_stage: active
name: dynamic_topoqa
