artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/465292636398478411/4d4f4ea0482d4af7bd4bf3c42b89f008/artifacts
end_time: 1764081400438
entry_point_name: ''
experiment_id: '465292636398478411'
lifecycle_stage: active
run_id: 4d4f4ea0482d4af7bd4bf3c42b89f008
run_name: polish_seed101_2025-11-25_13-50-51
source_name: ''
source_type: 4
source_version: ''
start_time: 1764078693079
status: 3
tags: []
user_id: vscode
