name: Update Traffic Badges
on:
  schedule:
    - cron: "0 14 * * *"   # Daily 14:00 UTC
  workflow_dispatch:

jobs:
  update-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Sanity check secrets (won't print them)
        run: |
          if [ -z "${{ secrets.GIST_TOKEN }}" ]; then
            echo "❌ GIST_TOKEN is missing."; exit 1; fi
          if [ -z "${{ secrets.TRAFFIC_TOKEN }}" ]; then
            echo "❌ TRAFFIC_TOKEN is missing."; exit 1; fi

      - name: Fetch repository traffic data
        env:
          GH_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
          OWNER:  ${{ github.repository_owner }}
          REPO:   ${{ github.event.repository.name || github.repository }}
        run: |
          set -euo pipefail
          # Trim owner if REPO came in as "owner/repo"
          if [[ "$REPO" == */* ]]; then REPO="${REPO#*/}"; fi
          echo "Using OWNER=$OWNER REPO=$REPO"

          mkdir -p traffic
          curl -fsSL -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/$OWNER/$REPO/traffic/clones" > traffic/clones.json
          curl -fsSL -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/$OWNER/$REPO/traffic/views"  > traffic/views.json

          echo "Raw clones.json:"; cat traffic/clones.json || true; echo
          echo "Raw views.json:";  cat traffic/views.json  || true; echo

          TOTAL_CLONES=$(jq -r '[.clones[].count] | add // 0' traffic/clones.json)
          TOTAL_VIEWS=$(jq -r '[.views[].count]  | add // 0' traffic/views.json)

          echo "TOTAL_CLONES=$TOTAL_CLONES" | tee -a $GITHUB_ENV
          echo "TOTAL_VIEWS=$TOTAL_VIEWS"   | tee -a $GITHUB_ENV
          echo "F_CLONES=${REPO}-clones.json" | tee -a $GITHUB_ENV
          echo "F_VIEWS=${REPO}-views.json"   | tee -a $GITHUB_ENV

      - name: Upload clones badge to Gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}             # classic PAT with "gist"
          gistID: 2b0de4f9f92a605b780e986e6d48ffcc    # your clones gist
          filename: ${{ env.F_CLONES }}               # e.g. QTopoQA-clones.json
          label: "clones"
          message: ${{ env.TOTAL_CLONES }}
          color: "blue"

      - name: Upload views badge to Gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}             # classic PAT with "gist"
          gistID: 9b749f24de62343dc995f8d524027c39    # your views gist
          filename: ${{ env.F_VIEWS }}                # e.g. QTopoQA-views.json
          label: "views"
          message: ${{ env.TOTAL_VIEWS }}
          color: "green"
