artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/651677857607399222/e61240c430224aff8b1f935ab80f3efe/artifacts
end_time: 1763912002434
entry_point_name: ''
experiment_id: '651677857607399222'
lifecycle_stage: active
run_id: e61240c430224aff8b1f935ab80f3efe
run_name: sched_boost_seed777_2025-11-23_15-10-14
source_name: ''
source_type: 4
source_version: ''
start_time: 1763910653056
status: 3
tags: []
user_id: vscode
