artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/783584035444777943/5aaf2d93a3e24a188deb90ca645e79e2/artifacts
end_time: 1765266076475
entry_point_name: ''
experiment_id: '783584035444777943'
lifecycle_stage: active
run_id: 5aaf2d93a3e24a188deb90ca645e79e2
run_name: large_batch_sched_boost_lean_seed222_2025-12-09_07-35-05
source_name: ''
source_type: 4
source_version: ''
start_time: 1765265710095
status: 3
tags: []
user_id: vscode
