artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/704094476654428691/563afadce3a94cb683e7c281f53909c1/artifacts
end_time: 1764702186675
entry_point_name: ''
experiment_id: '704094476654428691'
lifecycle_stage: active
run_id: 563afadce3a94cb683e7c281f53909c1
run_name: sched_boost_lean_seed222_2025-12-02_18-40-49
source_name: ''
source_type: 4
source_version: ''
start_time: 1764700856231
status: 3
tags: []
user_id: vscode
