artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/284713950887304746/5312d85efbd3407db47fa4165e9bfc4b/artifacts
end_time: 1763982054218
entry_point_name: ''
experiment_id: '284713950887304746'
lifecycle_stage: active
run_id: 5312d85efbd3407db47fa4165e9bfc4b
run_name: sched_boost_seed777_2025-11-24_10-38-11
source_name: ''
source_type: 4
source_version: ''
start_time: 1763980732054
status: 3
tags: []
user_id: vscode
