artifact_uri: /Volumes/PData/Data/Dev/Github/Repos/phd3/qtopo/QTopoQA/qtdaqa/new_dynamic_features/model_training/ml_runs/263834183455537235/66d9692bbc214365a09edb0e9917bd07/artifacts
end_time: 1763856650366
entry_point_name: ''
experiment_id: '263834183455537235'
lifecycle_stage: active
run_id: 66d9692bbc214365a09edb0e9917bd07
run_name: large_batch_sched_boost_seed777_2025-11-22_23-50-53
source_name: ''
source_type: 4
source_version: ''
start_time: 1763855478621
status: 3
tags: []
user_id: vscode
